### ISSUE TITLE
Does not retrieve anything

### ISSUE THREAD

**Issue by SearchAndDestroy** [IAmPicard/StarTrekTimelinesSpreadsheet#1]
I downloaded the latest release (0.3.1) and it seems to login correctly since I can see my avatar and level but tabs or anything else.
I also cloned the rep and tried `node sttsheet.js` but it outputs nothing at all.
`node sttsheet.js -g` returns that I am already in a gauntlet which is correct.

I am on node 8.4.0 64bit on Win10 Pro and I logged into the gave via Steam

**Comment by IAmPicard** [comment]
Do you have any frozen crew?

The code currently assumes there's at least one immortal / frozen crew on your roster, that could be why it gets stuck. I'll fix that now.

**Comment by SearchAndDestroy** [comment]
no I have no crew frozen but I have a few who are immortalized.
Thanks for fixing it :)

**Comment by IAmPicard** [comment]
I checked in a potential fix for it. Can you try syncing and seeing if that fixes the issue? I'll publish a new release if that did it.

**Comment by SearchAndDestroy** [comment]
i just updated and now `node sttsheet.js` is getting my crew :)

**Comment by IAmPicard** [comment]
Cool. Thanks for the test! I'll publish a new release now.
