### ISSUE TITLE
Ships - incorrect levels & missing ships

### ISSUE THREAD

**Issue by jaspotn** [IAmPicard/StarTrekTimelinesSpreadsheet#100]
**Describe the bug**
It appears that the ships tab is displaying incorrect and missing information.
The 1 star ship 'Constellation Class' is not shown at all and for every other while the rarity appears correct, the level stars are short by one.

**To Reproduce**
1. Go to 'Ships' tab
2. Click on 'Raity' column heading
3. Scroll down to 1 star listings
4. Notice the missing ship. Then notice that next ship listed (in my case Klingon K'Vort Bird-of-Prey) has only 6 stars when it should be 7. Level star values continue to be short for every other ship

**Expected behavior**
All ships should be listed and every ship should have stars should appropriate to its rarity.

**Screenshots**
![image](https://user-images.githubusercontent.com/39434813/42720761-bbbf8116-876c-11e8-85c1-b8aa1c2b0f81.png)
![image](https://user-images.githubusercontent.com/39434813/42720793-618171e0-876d-11e8-9a4e-c4bfcdb16f88.png)

**Additional context**

**Comment by IAmPicard** [comment]
Fixed in [release 0.7.7](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.7).

**Comment by anniemath** [comment]
This appears to still be an issue for the 1* Constellation Class. A fleetmate of mine reported that it doesn't show up under his ships tab, and I don't have it on mine either. I'm running 0.8.0. Terrific tool, by the way!

**Comment by IAmPicard** [comment]
Ok, I think I saw the issue. This 1* Constellation Class is not really an obtainable ship; I presume it's a ship that's given to anyone when they first join the game. What's happening on the backend is that I'm using the ship schematics to get the full list of ships, but there is no schematic for 1* constellation class, so the tool just doesn't show it.

It's not a generic "ship missing" bug, it's specific to this free, un-upgradeable one. I'll investigate if I can show it somehow even without schematic data.
