### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BrooklynKnight** [IAmPicard/StarTrekTimelinesSpreadsheet#101]
**Describe the bug**
After estimating a voyage and clicking start voyage, nothing happens and the voyage will not start.

**To Reproduce**
Open Program, or refresh if its been open a while, go to voyages, estimate a new voyage, click on start voyage.

**Expected behavior**
A new voyage to start with selected crew.

**Additional context**
This happened once or twice before but was resolved by rebooting. It's also happened once or twice if the crew it selected became unavailable (but that makes sense). All my crew is ready and waiting to start the voyage but it wont start.
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

**Comment by to11mtm** [comment]
Based on some checks in the debugger, the STT API is returning an 'inappropriate ship name' error.

**Comment by jaspotn** [comment]
Based on to11mtm's suggestion, I renamed a ship I was trying to send out from the default 'I.S.S. Enterprise NCC-1701' to just 'I.S.S Enterprise' and it sent. Mentioned this with bug #103 and changing the ship name also worked. Could it be hyphen or name character length?

**Comment by BrooklynKnight** [comment]
I think to11mtm is correct. I almost always have this issue now when the I.S.S. Enterprise is the default ship. An easy fix would be to make the name ISS Enterprise instead of the full name, which should fix it. 

Also making the ships clickable to choose which one you want when there are multiple options should help.

**Comment by IAmPicard** [comment]
This will display an error message in [release 0.7.7](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.7). It's not pretty yet, but at least it doesn't leave the UI in a confused state. I'll work on improving the error message to make it more actionable.
