### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by lobalope** [IAmPicard/StarTrekTimelinesSpreadsheet#105]
**Is your feature request related to a problem? Please describe.**
No problem, but wondering if there will be a new MacOS build?

**Describe the solution you'd like**
Would like a new MacOS build :-)

**Describe alternatives you've considered**
Keep using the current version.

**Additional context**
Tool version: **0.7.5**
Operating system: **darwin x64 (17.7.0)**

**Comment by gguynn** [comment]
I'd be happy to run builds at ops request.

**Comment by lobalope** [comment]
gguynn, would you be able to run a mac build for the latest release 0.7.9 please? thank you!

**Comment by IAmPicard** [comment]
I recommend using the [online version](https://iampicard.com) which provides almost the same functionality; I'll still attempt to produce the occasional mac build whenever I have access to a mac machine.
