### ISSUE TITLE
Feature request - Voyage recommendations option to consider Vaulted crew

### ISSUE THREAD

**Issue by Darxide23** [IAmPicard/StarTrekTimelinesSpreadsheet#107]
**Is your feature request related to a problem? Please describe.**
Not specifically, but suboptimal voyages happen without considering all available crew.

**Describe the solution you'd like**
An option to tell the voyage recommendation to consider crew that's frozen in the vault in addition to active crew

**Describe alternatives you've considered**
There aren't any?

**Additional context**
Nope.
Tool version: **0.7.6**
Operating system: **win32 x64 (6.1.7601)**

Thanks! :smile:

**Comment by Gryphonsdream** [comment]
i think i recall where this use to be but 
it was removed at some point, not sure why.
i recall you asking how i calculate my arena and how i used the data in excel
i could send you my excel file, thoe there are a lot of changable numbers for caculations given total crew space available

**Comment by Darxide23** [comment]
I'll take any kind of spreadsheet you want to send me. Can never have enough tools.

**Comment by Gryphonsdream** [comment]
k i cleaned up my spread sheet a little, and posted it to my one drive if you want to use or look at how i calculate who i keep on or freeze. i use it in conjunction with STT Crew Manager.
IAmPicard you are awesome.
https://1drv.ms/x/s!AvV7IjxowIkH4TAMu8TKlGTmw1KV

**Comment by Darxide23** [comment]
You're both awesome. Thanks for the sheet, Gryphon.

**Comment by ThePooBurner** [comment]
Should this be closed?  There is a button for this in the GUI now.

**Comment by IAmPicard** [comment]
Yup, fixed in 0.7.6
