### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by whobutdrew** [IAmPicard/StarTrekTimelinesSpreadsheet#108]
**Describe the bug**
Under Missions, under the Celestial Temple mission "Serious Business," I am told that I have no crew capable of completing the mission.

**To Reproduce**
Click on Missions, check "only those not completed," navigate to specified mission.

**Expected behavior**
I have since cleared the Normal difficulty to 3 stars, so at the very least, my team of (Talos IV Spock), (Dabo Girl Leeta), and (Away Team Archer) should have been presented as possibilities.

**Screenshots**

**Additional context**
I only want to add how wonderful this program is!  I created an Access DB to help me do many of the things that your application does much more easily/better.  Thank you!  I'll be getting you a coffee when I get paid.
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

**Comment by whobutdrew** [comment]
I forgot to say that I did hit Refresh to ensure that the data was up to date (I had recently leveled up Archer) and the app was not open on my phone.

**Comment by IAmPicard** [comment]
The calculations there only take "elite" into account. That is, crew you'd need to complete all 3 mastery levels. I'll add a note to make that aspect clear. Relevant code bit [here](https://github.com/IAmPicard/STTApi/blob/7d5b97120fcb236a683855b1301e1606620a130e/lib/MissionCrewSuccess.ts#L52)
