### ISSUE TITLE
Feature request - In the Items tab, where Type = Schematics, put a * next to the Quantity if the ship is fully maxxed out

### ISSUE THREAD

**Issue by TheMegaSage** [IAmPicard/StarTrekTimelinesSpreadsheet#109]
**Describe the solution you'd like**
Ship schematics can be used for replication fuel. It would be nice to have a visual indicator (such as a * beside the number in the quantity column) if that ship has maximum stars and cannot be increased further. That will allow the player to use the schematics for other means without extra searching.

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (6.1.7601)**

**Comment by gguynn** [comment]
√ Added to the `Ships` list instead of `Items`.  I'll submit this feature with my next pull request to admin.  ~Cheers!

![screen shot 2018-08-09 at 6 04 28 pm](https://user-images.githubusercontent.com/1015228/43938340-cb0e5cf4-9bfe-11e8-858f-6271904b606b.png)

**Comment by IAmPicard** [comment]
That doesn't help with identifying the items too much.

I think what we want for this feature is an extra tab somewhere with "Items you can safely throw in the replicator", which includes schematics for maxed-out ships as well as (maybe) equipment for FF/FE crew.

**Comment by gguynn** [comment]
👍

**Comment by lordasti** [comment]
How about this?
Printing the number of schematics for each ship at least let you see witch ones could be safely thrown and provides useful information per se
![image](https://user-images.githubusercontent.com/8685107/44415702-60e04c80-a571-11e8-8b04-69f983e9fb39.png)

the code is pretty easy, see #137

**Comment by IAmPicard** [comment]
Number of schematics was added to the ship table as above.
