### ISSUE TITLE
Filtering needed equipment by crew marked as favorite

### ISSUE THREAD

**Issue by gguynn** [IAmPicard/StarTrekTimelinesSpreadsheet#110]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
I love Needed Equipment recommendations.  Could you please add a filter to: filter needed equipment for only crew who are marked as favorite?

**Describe alternatives you've considered**
Editing the source code - but I don't know where I would start.

**Additional context**
I'm running the source code on my Mac with node.  You software is awesome.  Thank you!

**Comment by IAmPicard** [comment]
Hey, that's a good start. Do you want to polish it up and send a PR?

**Comment by gguynn** [comment]
Awesome, thanks!  I would be happy to give it a shot.  I recommend you make the additions to **/STTApi/blob/master/lib/CrewTools.ts** yourself since you'll just need to add `rosterEntry.favorite = crew.favorite;`

I'll add the checkbox and method for **/StarTrekTimelinesSpreadsheet/blob/master/src/components/CrewRecommendations.js** and submit a pull request.  Thanks again for your hard work on this project.  ~Cheers!

**Comment by gguynn** [comment]
Actually, I've got my workspace setup now.  I'll make both changes and submit a pull request.  I'll try to tackle some of these other issues and feature requests too.  ~Cheers!

**Comment by gguynn** [comment]
Pull request submitted for both repos.

Pull request for /StarTrekTimelinesSpreadsheet/ depends on pull request @ /STTApi/

Issue is closed as since there's a a pending pull request.  ~Cheers!
