### ISSUE TITLE
Feature request: Equipment recommendations for all levels, not just current bracket

### ISSUE THREAD

**Issue by ThePooBurner** [IAmPicard/StarTrekTimelinesSpreadsheet#111]
**Is your feature request related to a problem? Please describe.**
No it isn't.

**Describe the solution you'd like**
If i understand the new Needed Equipment feature, it will tell me what i need for only the current level brackets of my characters (ie: to go from 50-60 for crew A, from 30-40 for crew b, etc. for whatever bracket they are currently in). It would be extremely awesome if this could instead, based on the known item recipees and item needs, tell me everything i am going to need to take all of my crew from where they are to lvl100 FE, so that i can know upfront that i don't just need 90 0* databases, but that i actually need 356 (or whatever the number may be.)

This would be beyond awesome because then i could just sit and farm adnausium until i had everything i needed. Then i could just sit and level up everyone in one go and have all characters 100FE (assuming i had enough trainers).  Once everyone is 100FE, when i get a new crew and they are the only one not 100FE, using the tool would tell me everything i would need to take that 1 character to 100FE, speeding up my farming dramatically.

The leveling of characters would go smoother with this, since when i level a crew i tend to go for broke and just do 1 character until i can't go anymore, which usually takes needed items away from the other crew that also said they could be upgraded. So i end up going from 30 people displaying the ability to be upgraded to just 5 or so after i finishing topping out the 1.

**Describe alternatives you've considered**
I wish even just your current implementation were part of the game itself. You're amazing.

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
I got this request before. Unfortunately, the game API doesn't give me more information except for what's needed to go over to the next tier (from 50 to 60, etc.);

It could rely on some external source of information (like the wiki), but I've been burned before and opted to rely only on the game API itself. The wiki is good for a human to read, but not great for code to understand (the data is not structured nor complete, and oftentimes incorrect or out of date)

**Comment by Gryphonsdream** [comment]
i would have to agree with IAmPicard on this, i too have found times where the wiki data is not fully upto date, but perhaps a possible altrnative might be to provide a link to the behold helper page. so that peeps might just look it up for them selves.

**Comment by ThePooBurner** [comment]
Is there any way to petition DB to make the information available to the API? Is there official API documentation available, or did you develop the API you use yourself through packet snooping?  It seems like a full inventory of what they need should be something that they could code into some sort of easily sendable hash.  Or perhaps you could start generating your own recipe database from information retrieved at each level bracket from program users that’s submitted back to the project via JSON?
 
Or is there a way to change the wiki into a more easily read format so that it could be used for an initial database build that is then updated via the above suggested user data?

**Comment by IAmPicard** [comment]
They don't publish an API documentation, and don't take custom requests for API expansions, unfortunately.

Yes, attempting to recreate the data from users may work, but we need a lot more scale to get the data, an actual web service somewhere to compose it, and there will always be holes regardless.

You can create the recipe tree for equipment, but the missing info is what equipment is needed for each slot of each crew at each 10-level interval.

**Comment by ThePooBurner** [comment]
Well dang. Well, in that case i will just have to stick with what you have and make a different enhancement suggestion thread for the next thing i would love to have from the equipment needed tool.

**Comment by ThePooBurner** [comment]
Is there a way to request a particular item by item code?  For instance, most crew members have stuff that is unique to them and it's expected that there will be a 5* version of their uniform or whatever. So is there any way to "datamine" for the other items that we would expect to see for a particular crew member?  Like, even in the local game data like they do after patch-day in WoW?

**Comment by ThePooBurner** [comment]
Like for instance, get an item list from local game data, then just request the recipees for every item in the list through the API, then extrapolate items needed based on crew member's name being a part of said item's name.

**Comment by IAmPicard** [comment]
In the next release, I've included an experimental feature for querying data for all levels, based on crowd-sourced cache. Not quite as reliable as the game API, but may provide some level of functionality for this.
