### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mhabiby1** [IAmPicard/StarTrekTimelinesSpreadsheet#113]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

Error details: Error: Network error; status 500; reply NoMethodError (undefined method `id' for nil:NilClass):
app/models/conflict/status.rb:365:in `block in pending_rewards'
app/models/conflict/status.rb:364:in `map'
app/models/conflict/status.rb:364:in `pending_rewards'
app/models/conflict/status.rb:396:in `get_description'
app/models/character.rb:192:in `full_description'
app/models/player.rb:91:in `to_hash'
app/controllers/player_controller.rb:240:in `block in index'
app/models/change_tracker.rb:10:in `track'
app/controllers/player_controller.rb:239:in `index'
app/controllers/application_controller.rb:45:in `record_client_api'
app/controllers/application_controller.rb:30:in `purge_thread_around'.

**Comment by IAmPicard** [comment]
I suspect this is some sort of random one-time fluke, possibly related to a server error. If you continue seeing it, can you send any more details? For example, does the game itself work in the same network?

**Comment by Mhabiby1** [comment]
I can share with you the fact that I have in installed and uninstalled this
program 3 or 4 times and I still get the same error message.

I'm running a laptop with Windows 10 64-bit also should be known that I'm
running exactly the same operating system on my desktop and I'm not having
any problems.

Is there an issue that we can only run one instance of your app? And no I'm
not running them simultaneously, I don't run any of the viewer
simultaneously.

**Comment by IAmPicard** [comment]
Can you try uninstalling the tool, then deleting the "%APPDATA%\Star Trek Timelines Crew Management\" folder and reinstalling?

There shouldn't be an issue with installing / running the tool on several machines.

**Comment by Mhabiby1** [comment]
You have been great, and I do appreciate your help.
I removed the appdata folder (it was in roaming FYI)
Reinstalled the program.
Got this
[image: Screenshot_1.jpg]
