### ISSUE TITLE
Feature Enhancement: Needed equipment, missions clickable to run missions with warp.

### ISSUE THREAD

**Issue by ThePooBurner** [IAmPicard/StarTrekTimelinesSpreadsheet#114]
**Is your feature request related to a problem? Please describe.**
Yes, time savings.

**Describe the solution you'd like**
The needed equipment tool is something that i had been wanting to create a program to do for a while. A "shopping list" like this in the regular game client is a feature i've requested from DB.  It's great, but it's hard to take action on.  When the information is exported to CSV it's a bit clunky to read and then have to go into the real game client to warp the missions needed to bring up the total. And then i have to count how many i see in my results, then reference back to the spread sheet, and then go into the tool and update the totals again to see where i'm actually at vs what i thought i counted.

To make this tool way more effective, it would be more than awesome to be able to click on the mission title next to the items, and then run them with warp 1/10, with the item numbers for the needed equipment being updated after each warp so we could see in real time how much more we need.  This would make the tool dramatically more effective, and significantly more useful and user friendly.

**Describe alternatives you've considered**
None. Being able to warp missions from this tool rather than having to jump back into the real game client would just be awesome.

**Comment by IAmPicard** [comment]
This feature will be available in the next version, it's checked in.
