### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by UpScope** [IAmPicard/StarTrekTimelinesSpreadsheet#116]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

Error details: TypeError: Cannot read property 'archetypes' of undefined

**Comment by IAmPicard** [comment]
I suspect this is some sort of random one-time fluke, possibly related to a server error. If you continue seeing it, can you send any more details? For example, does the game itself work in the same network?
