### ISSUE TITLE
voyages wont send due to name length...

### ISSUE THREAD

**Issue by wizzdome** [IAmPicard/StarTrekTimelinesSpreadsheet#119]
Hey, I am not sure if this was addressed in this newest release... But When sending a ship with a long default name.... it wont send it with the default name... However if you shorten the default name and customize it, it sends perfectly fine. The ship that i have noticed this with that pops up the most for me is the I.S.S. Enterprise NCC - 1701... I normally just shorten it to I.S.S. which sends just fine. Not sure why it would not send with default name... anyhow... I also want to say thank you for this awesome tool it has been extremely helpful to me since i started using it... Big Kudos!!!

**Comment by IAmPicard** [comment]
I think it's the dash ('-') character it doesn't like. FWIW, this is a strange one, as the error message that comes back is not a normal error message (not a Json string), but rather it looks like an internal server callstack. So it's not very pretty when it happens (it'll be a message bar at the top of the voyage page claiming it can't decode a json string).

I'll look into special-casing this particular server error message and making it prettier on the client side.

**Comment by fyreflow** [comment]
For what it's worth, some players have reported an issue with sending out the IKS T'Ong with its default name using the official app. Perhaps the apostrophe also causes issues?

**Comment by wizzdome** [comment]
I just tested out sending the iss with just deleting the 1701 so all the way up to the dash including the - and it sent. I tried at first just deleting the 1 which didn't work. I will keep my eye open for t'Ong in the future.

**Comment by IAmPicard** [comment]
This was fixed by defaulting to an empty ship name (which the game interprets as the actual ship name), this emulates what the game client does.
