### ISSUE TITLE
Feature Request: Show needed items that are obtainable through faction missions only

### ISSUE THREAD

**Issue by lordasti** [IAmPicard/StarTrekTimelinesSpreadsheet#121]
It would be ideal to filter needed equipment to show those that are only obtainable through faction mission and plan accordingly in this way to check the faction store or launch the appropiate faction mission.

A simple check in the needed equipment recommendations should be sufficient.

Consider other filters such as "Obtainable through missions" or "Obtainable through ship battles" to plan ahead for the daily mission accomplishment

**Comment by lordasti** [comment]
Added PR https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/pull/122

**Comment by IAmPicard** [comment]
Closing as fixed
