### ISSUE TITLE
Gauntlet cheating?

### ISSUE THREAD

**Issue by nikdollas** [IAmPicard/StarTrekTimelinesSpreadsheet#123]
Stange things are happening in gauntlets, you calculate a95% chance of victory and I loose. Not your fault I guess but could you have a look into that?
Thanks
[gauntlet_32.xlsx](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/files/2290330/gauntlet_32.xlsx)

**Comment by fyreflow** [comment]
I haven't done any coding on this.  The credit should all go to @IAmPicard and those who have contributed.

Just adding my observations to your report. :smirk:

**Comment by IAmPicard** [comment]
83 is a too small sample size. FWIW, @peachtreerex used the log feature to look at 1000+ rounds and found the results overall to be inline with calculated chance percentage: https://forum.disruptorbeam.com/stt/discussion/10548/1000-gauntlet-rounds-of-data

I'm pretty confident there's no "cheating" on DB's side and no miscalculation on the app side (give or take 3% given the Monte Carlo solution I'm using), it's just biased opinions (which BTW, I sometimes get as well... I've definitely seen a 99% loss which is very frustrating even though it's statistically valid).

**Comment by Gryphonsdream** [comment]
i dont think the Tool so much as DB out put of the number displayed
in the game it self i have observed times where DB will show oponent stats that are way low.
like 1 to 200 max on all stats when the actul numbers are more like 1020 to 1200
and you dont get to find this out till after the match is accepted. by then its to late.
ussually this is an issue where the stat numbers are over 1000.
again this is not the tools issue of reading the data, but DB not outputing the right numbers.
i have seen this about 1 in maybe 50 matches, so would crtainly acount for the 95% loss issue if that is what is happening. and reporting it to DB, is sometimes like telling a child its bed time right after they woke and want to play.

**Comment by IAmPicard** [comment]
Closing this for now. See analysis done by Peachtree [on the forums](https://forum.disruptorbeam.com/stt/discussion/11125/2500-rounds-of-gauntlet-data) which indicate the percentage is pretty much spot-on (within error margin).
