### ISSUE TITLE
Lock Crew Spreadsheet Columns

### ISSUE THREAD

**Issue by TravisSMcClain** [IAmPicard/StarTrekTimelinesSpreadsheet#129]
Could the column tabs in the Crew tab be fixed in place? Sometimes I forget when scrolling which column is which thing.
![crew management column headers](https://user-images.githubusercontent.com/42441268/44210192-ce384b80-a133-11e8-831b-09992dfb68ed.jpg)

**Comment by ThePooBurner** [comment]
I would like that for every view.  Also scroll bars.

**Comment by IAmPicard** [comment]
This is now implemented on most tables in the tool.
