### ISSUE TITLE
Move Gauntlet Reload Button

### ISSUE THREAD

**Issue by TravisSMcClain** [IAmPicard/StarTrekTimelinesSpreadsheet#130]
Could the Reload Data button in the Gauntlet tab be moved down? Presently, if I scroll down to review more matches than just the top row, it takes me too far down to still access that button without having to scroll up again.
![crew management gauntlet reload data](https://user-images.githubusercontent.com/42441268/44210286-063f8e80-a134-11e8-9db8-35e09de52aa2.jpg)

**Comment by lordasti** [comment]
I totally agree with this!. Will provide a PR shortly.

PS: please to meet you here Travis!

**Comment by lordasti** [comment]
Added #131

**Comment by IAmPicard** [comment]
Closing as fixed
