### ISSUE TITLE
Bug report: Unable to Login with Facebook

### ISSUE THREAD

**Issue by aeternalia** [IAmPicard/StarTrekTimelinesSpreadsheet#132]
**Describe the bug**
Unable to Login with Facebook.

**To Reproduce**
Steps to reproduce the behavior: (1) open app, (2) login with Facebook, (3) nothing happens.

**Expected behavior**
Er, to login?

**Screenshots**
(1)
![open app](https://user-images.githubusercontent.com/42445074/44220997-309e4580-a14e-11e8-86b4-4ca3626327bb.PNG)

(2)
![connect with facebook](https://user-images.githubusercontent.com/42445074/44221008-3562f980-a14e-11e8-9aa8-c33dd04a88ee.PNG)

(3)
![nothing happens](https://user-images.githubusercontent.com/42445074/44221016-3a27ad80-a14e-11e8-997f-253fa12b653d.PNG)

**Additional context**
Tool version: **0.7.7**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
This is related to the new electron 3.0 ; I need to go back to 2.0 until I can figure out why redirects don't work.

**Comment by IAmPicard** [comment]
Logged [bug in Electron](https://github.com/electron/electron/issues/14142) for this issue.
