### ISSUE TITLE
Feature request: Gauntlet QoL suggestion

### ISSUE THREAD

**Issue by Darxide23** [IAmPicard/StarTrekTimelinesSpreadsheet#134]
Just a couple of small QoL suggestions for the Gauntlet tab. I think it would be helpful if the primary stat for the gauntlet was still shown after you begin. If I'm going for high score and not a streak, it's helpful to burn weaker cards rather than paying the 50 merit refresh cost. Knowing the primary stat can help make a more informed decision.

Also, it would be very helpful if the current crit% was also displayed on the matchup tiles at the bottom for the same reason. https://i.imgur.com/8DxQa6r.png

**Comment by ThePooBurner** [comment]
I actually found that this would be helpful for me recently.

**Comment by IAmPicard** [comment]
Some of this was implemented in the last release
