### ISSUE TITLE
Bug report: Error starting Voyages

### ISSUE THREAD

**Issue by Darxide23** [IAmPicard/StarTrekTimelinesSpreadsheet#138]
**Describe the bug**
Attempting to start a Voyage often results in a "Error: Unexpected token A in JSON at position 0" message.

**To Reproduce**
Unknown. Happens sometimes while starting a Voyage.

**Expected behavior**
Voyage should start.

**Screenshots**
N/A

**Additional context**
No crew on shuttles and not trying to use vaulted crew. Have restarted the Crew Manager. Not logged into the game from any other source at the time. Seems to happen at random. I can't replicate it on demand. Probably 50/50 of all Voyage start attempts fail with this error. This error did not happen in 0.7.6.
Tool version: **0.7.7**
Operating system: **win32 x64 (6.1.7601)**

**Comment by jaspotn** [comment]
Check the ship you are using, if it's ISS Enterprise NCC-1701,  remove the
'-1701' or completely rename it. Happens I think with a ship name with an
apostrophe

**Comment by Darxide23** [comment]
You might be right. I just checked and this Voyage the Crew Manager was trying to send the I.S.S. Enterprise NCC-1701. I'll have to keep an eye on that. If that's actually the problem then it should be a pretty easy fix.

**Comment by beertastic** [comment]
When I click on calculate voyage.. I see nothing. I tried ensuring that I've no '
Stil nothing.
In the network chrome tab, its' loading:
wasmWorker.js
Then returning two copies of:
voymod.wasm

Thoughts?

**Comment by Darxide23** [comment]
It isn't the apostrophe that prevents it, it's a hyphen.

**Comment by beertastic** [comment]
I really must learn to read properly... :)
Cool, I still can't generate a voyage crew though... shame, would be a great feature.

**Comment by Darxide23** [comment]
Try reinstalling because it works fine otherwise.

**Comment by IAmPicard** [comment]
Are you using the web version or the desktop version? Confused about the chrome devtools note.

If you're using the web version, which version of chrome are you running, and which OS?

And since you mentioned devtools, do you see any errors in the console when you click Calculate?

**Comment by beertastic** [comment]
Web.
Ubuntu 18.04
chrome: Version 69.0.3497.92 (Official Build) (64-bit)
Console output when clicking auto generate:

wasmWorker.js:1 Uncaught (in promise) abort({"name":"BindingError","message":"String has UTF-16 code units that do not fit in 8 bits","stack":"BindingError: String has UTF-16 code units that do not fit in 8 bits\n    at BindingError.<anonymous> (https://iampicard.com/wasmWorker.js:8:228957)\n    at new BindingError (eval at at (https://iampicard.com/wasmWorker.js:8:228768), <anonymous>:4:34)\n    at ct (https://iampicard.com/wasmWorker.js:8:229268)\n    at Object.toWireType (https://iampicard.com/wasmWorker.js:8:277231)\n    at Object.calculate (eval at ir (https://iampicard.com/wasmWorker.js:8:238623), <anonymous>:7:26)\n    at n.then.t (https://iampicard.com/wasmWorker.js:8:158364)\n    at Object.o.onRuntimeInitialized (https://iampicard.com/wasmWorker.js:8:318418)\n    at t (https://iampicard.com/wasmWorker.js:8:318608)\n    at Fn (https://iampicard.com/wasmWorker.js:8:319227)\n    at e (https://iampicard.com/wasmWorker.js:8:319267)"}) at Error

**Comment by beertastic** [comment]
I've got 350 characters, maybe that is an issue?

**Comment by IAmPicard** [comment]
The original bug here is fixed; the web bug is not quite understood, but we can follow up on the other issue.
