### ISSUE TITLE
Feature Request: Expanding on Crew Dismissal tool

### ISSUE THREAD

**Issue by CaptainSiskoAA** [IAmPicard/StarTrekTimelinesSpreadsheet#139]
Hi, dismissing extra crew when opening packs has always been time consuming and I was thrilled to hear that this feature made it in to your tool.

I'm hoping it can be expanded, since it currently only shows about 4 lines and cannot currently be resized.  It would be helpful to show more lines as the window expands.

Also hoping for a Filter feature, and the ability to select all on screen, such as being able to select all Level 1 crew simultaneously and dismiss.

Thank you as always for your hard work, this tool is amazing!

Matt
Captain Sisko [AA]

**Comment by IAmPicard** [comment]
In [release 0.8.2](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.8.2), the tool will auto-select most likely dismissal candidates (dupes with level 1 and rarity 1), so it should be a quick scan over the table and hit the dismiss button to get rid of all honor fodder.
