### ISSUE TITLE
stuck at 1156/1158 crew images

### ISSUE THREAD

**Issue by ChewableCPP** [IAmPicard/StarTrekTimelinesSpreadsheet#14]
I'm seeing this happen frequently with the dev build:

![image](https://user-images.githubusercontent.com/34800071/36999605-7f2070c0-2075-11e8-9403-63428a038d6f.png)

I don't know what causes it. I've only seen it with the current master, I think. But when it happens, anecdotally starting up the previous release binary clears it up (even after exiting both and starting the dev build).

**Comment by ChewableCPP** [comment]
This is happening seemingly 100% of the time now.

**Comment by ChewableCPP** [comment]
I believe now that downloads are completely broken in the current version.

Using a previous version works around it because it caches all of them so the new version does not need to download them at all.

**Comment by IAmPicard** [comment]
This is related to a bug in webpack: https://github.com/webpack/webpack/issues/6642

I'll check in the suggested workaround from there.

**Comment by IAmPicard** [comment]
Should be fixed with cce5d31dae154e402a94e5153b7a997f7cd02a7b

**Comment by ChewableCPP** [comment]
Yep, it's fixed.
