### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Koregano** [IAmPicard/StarTrekTimelinesSpreadsheet#141]
**Describe the bug**
When opening initially, receive the error "Cannot read properly the 'archetypes' of undefined"

**To Reproduce**
Opening the program from the first time and every time

**Expected behavior**
The program never quite loads.  It stops at the screenshot below.

**Screenshots**

![image](https://user-images.githubusercontent.com/42690009/44615404-ebf36800-a839-11e8-8026-099e0dc3d381.png)

**Additional context**
Tool version: **0.7.7**
Operating system: **win32 x64 (10.0.17134)**

Error details: TypeError: Cannot read property 'archetypes' of undefined

**Comment by IAmPicard** [comment]
This was probably a random fluke; if the error persists, can you try uninstalling the tool, then deleting the "%APPDATA%\Star Trek Timelines Crew Management" folder and reinstalling?
