### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by PsionStorm** [IAmPicard/StarTrekTimelinesSpreadsheet#142]
**Describe the bug**
When trying to send a voyage, getting an error "Error: Unexpected token A in JSON at position 0" and the voyage does not launch.

**To Reproduce**
Open program.
Click voyage tab.
Calculate best crew selection.
Start voyage with recommendations.

**Expected behavior**
I expected the voyage to launch. :(

**Screenshots**
![image](https://user-images.githubusercontent.com/42592927/44621560-1cf18e00-a876-11e8-8faa-64b9b4186cf6.png)

Attached.
**Additional context**
Tool version: **0.7.7**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
Please change the ship name; for some reason, DB really doesn't like the dash ('-' character) in there. I'll try to make the error message more descriptive.

**Comment by PsionStorm** [comment]
That seems to have fixed it. Thank you!

**Comment by IAmPicard** [comment]
FWIW, in the new release this issue should be fixed; unless you intentionally change the ship name to something unsupported the default will always work.

**Comment by PsionStorm** [comment]
Sounds great. Thank you!
