### ISSUE TITLE
Crew Tab Dropdown for 100 Rows per page Bug

### ISSUE THREAD

**Issue by AricCougar** [IAmPicard/StarTrekTimelinesSpreadsheet#146]
When clicking the dropdown for showing 100 crew members per page on the crew tab, it still shows the original 50, and adds 50 additional lines of blank space (no additional crew shows up.  However, the Number of pages does appear to drop in half as expected.

1. Go to the Crew Tab.  (this assumes you have more than 100 crew on the account being tested).
2. Scroll down to bottom (below the 50).
3. Click the Dropdown option from 50 to 100 (to view 100 crew per page).
4. Now scroll down to see the additional crew, and notice the bug.  There is no crew, just blank space where crew should be after the original 50th crew (which still shows fine). 

It should immediately show allow you to scroll the page down to see the newly available next 50 crew on the same page with the previous 50.  It should not show 50 blank lines.

![crew tab dropdown for 100 rows per page bug](https://user-images.githubusercontent.com/42733197/44648708-1f9bd280-a99f-11e8-811f-6f1f4dd15223.GIF)

Additionally, leaving and going back to the crew tab, seems to restore the original 50 rows, and forget that you changed it.

**Comment by PhantumPhysics** [comment]
I can confirm this also, from when I started using the tool about 3 versions ago

**Comment by IAmPicard** [comment]
I removed the row-per-page option as I couldn't get it to work correctly. It'll be 50 per page, or no pager if the total list is under 50.
