### ISSUE TITLE
Tools Dropdown - Sort via Rarity (to re-add feature)

### ISSUE THREAD

**Issue by stargazer001** [IAmPicard/StarTrekTimelinesSpreadsheet#159]
**A streamlined way to check on your totals for crew** and a handy collapsible view.

I just noticed with the new update, so have chosen to go back to version 0.7.5 that has it available, hopefully it can be added back to the 'tools' new setup.

**Additional**
![stt tool](https://user-images.githubusercontent.com/35642974/45199542-95614180-b2af-11e8-9df6-920ccccaa567.JPG)

TIA 
nb: _hopeful_ - also congrats on a great app!

**Comment by stargazer001** [comment]
Sad, so by 'closed' it's not on the list to make a comeback?

Guess I can keep on using the older version (as I use this feature a lot) For searching via Rarity and collapsible - makes it a faster process

**Comment by IAmPicard** [comment]
This is fixed in the repo, as the change number suggests. If you build from source, it's there now. Otherwise it will be available in the next release (0.8.1).

You can't use the old version as login won't succeed (due to DB switching to client 6.0.0)

**Comment by stargazer001** [comment]
I don't use it much, but do like to sort them for sure, so look forward to the next release.

_Hadn't added that I only ever use the desktop app._

_cheers_

**Comment by IAmPicard** [comment]
Didn't get around to make a new build. The [web version](http://iampicard.com) has all the latest changes too.
