### ISSUE TITLE
Item list "Export to CSV" does not include a field for Cadet Missions that produce the item.

### ISSUE THREAD

**Issue by PhantumPhysics** [IAmPicard/StarTrekTimelinesSpreadsheet#160]
**Describe the bug**
Exporting the item list to CSV does not include the Cadet Missions

**To Reproduce**
1. Go to '...' menu,  select "items"
2. Click on 'Export CSV'
3. save file, then open in an external editor or spreadsheet.
4. See the csv list is missing the cadet missions that produce the item.
5. All the other fields displayed in the program item list are there.

**Expected behavior**
Export to CSV should include the field "Cadet Missions"

**Additional context**
I tried some filter options but no difference.  I also searched the exported data for some cadet missions to verify the cadet missions were not included in another column.  The exported data is otherwise complete.

**Comment by IAmPicard** [comment]
Fix was checked in. This will be available in the next release.

**Comment by PhantumPhysics** [comment]
Thank you very much!
