### ISSUE TITLE
Feature request: Guantless match up filtering

### ISSUE THREAD

**Issue by ThePooBurner** [IAmPicard/StarTrekTimelinesSpreadsheet#167]
**Is your feature request related to a problem? Please describe.**
It would be really nice to be able to filter out any gauntlet match-ups that don't fall within specified parameters, and also be able to sort by points available rather than (or in addition to) win percentage.

**Describe the solution you'd like**
I would like a box where i can specify a minimum win percentage to have the match-up displayed or not. I will never fight anyone below 65%, so it would be nice if i could filter out all match ups below that so that i have less clutter when trying to decide which match up to do.

Additionally, have a dropdown list to select one of 4 possible sorting methods: Win percent chance, Points winnable, Percent & Points, Points & Percent.
For instance, say the first 6 match-ups listed are all a 100% chance to win, but the 1st-3rd only offer 10 points for winning, but the 4th offers 95. So if i had the 3rd sorting option selected that 100% with 95 points would be listed first rather than 4th. It would make it quicker and easier to find the match-ups that i want to do.
With the 4th option selected the matchup with the highest points with the highest percentage would be listed first. IE: the circled matchup below would be listed first because it the higher points at the highest percentage.
![image](https://user-images.githubusercontent.com/42203117/45575675-9d7e2b80-b831-11e8-9996-6f80d8cdd309.png)

**Describe alternatives you've considered**
Manually looking through everything ever time for the best combination of points and win percentage.

**Additional context**
Tool version: **0.7.9**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
Not quite as you described it, but I added a setting that will sort the matches by best" first, which I defined as sorting by "chance + points / 4".
