### ISSUE TITLE
Gauntlet functionality not responsive

### ISSUE THREAD

**Issue by Brian-Ballard** [IAmPicard/StarTrekTimelinesSpreadsheet#168]
**Describe the bug**
In both the web and desktop tools (win 8.1) the gauntlet page does not update after selecting a match up or choosing to refresh with merits.  The buttons only seem to perform their in game funtion part of the time as well. 

**To Reproduce**
Enter the Gauntlet page.  Select a matchup to play or merit refresh.

**Expected behavior**
Screen to update with new match ups.  Show results of previous matchup if chosen.

**Screenshots**

**Additional context**

**Comment by IAmPicard** [comment]
The perf is somewhat improved in [release 0.8.0](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.8.0), but I could still work on the UX to show a loading state (spinner) or something to that effect.

**Comment by Brian-Ballard** [comment]
Thanks. I think my issues were due an account bifurcation via different account linking. Facebook login vs email.  In the middle of the bifurcation my main app went to email connect and my FB connected iampicard tool started a gauntlet it could only access and unreliably at that. Now my gauntlet is unusable and I am waiting to hear back from DB CS.

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 27, 2018 at 12:14 AM, IAmPicard<notifications@github.com> wrote:   
The perf is somewhat improved in release 0.8.0, but I could still work on the UX to show a loading state (spinner) or something to that effect.

**Comment by IAmPicard** [comment]
Gauntlet UX and perf was improved further in 0.8.1, and per above the issue was unrelated.
