### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Nothsor** [IAmPicard/StarTrekTimelinesSpreadsheet#170]
**Describe the bug**
there appears to be a bug when you start a voyage with the ISS Enterprise. It states there is an invlid name

**To Reproduce**
Start a mission with ISS Enterprise Ncc-1701 (default name)

**Expected behavior**
Expected voyage to start

**Screenshots**

**Additional context**
Tool version: **0.7.9**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
The fix for this is checked in and will be available in the next release. Already available in the [online version](https://iampicard.com).

To workaround, just rename the ship before pressing start. Any (clean) string without dots (.) or dashes (-) will work.
