### ISSUE TITLE
Voyage Crew Skill Combo Strength/Weakness

### ISSUE THREAD

**Issue by pim69** [IAmPicard/StarTrekTimelinesSpreadsheet#172]
problem to address:
As part of selecting crew in a behold/begold, we generally consider 2 things: strength of the crew offered (good tools out there for this), as well as deficiencies in our existing crew.  Determining our crew deficiencies in voyages can be quite difficult, unless you've recently had a Eng/Sec voyage for example and know you have difficulty hitting 8 hours.

requested feature:
Ability to select any voyage skill combo (such as eng/sec above) independent of the current voyage available, to see what your current crew is capable of reaching in a voyage.  Obviously traits throw some variables into this, but your base strength of crew would give good assistance in crew selection both for beholds AND for selecting who to citation next.

alternatives considered:
There are good tools out there for looking at the individual crew strength of one crew.  You can get a rough idea of weaknesses by counting up how many eng/sec combo crew you have, and how many strong voyage crew you've got but it's a very rough estimate and hard to make a good decision this way (especially with mixed FF status crew).

edit: Would be useful to have a quick reference of all the skill combos ranked, from strongest to weakest, as well as being able to pull up the actual crew collection making up the strong/weak members pretending that traits are not a factor.

**Comment by paulbilnoski** [comment]
In the app version (not available in web version) the bottom of the voyage estimation calculator has a button to "Export CSV with crew Voyage ranking..." which computes voyage estimates for all skill pair combos for your crew. Does this give what you want, or do you have suggestions for improvement?

**Comment by paulbilnoski** [comment]
The export should provide two CSV files, the first contains crew (with the "alt1", "alt2" columns) and the second contains estimated voyage times for all skill pairs and the crew that accomplished it, ignoring traits. I'll need to dig into what the columns mean for the first sheet export, but generally it ranks each crew by skill for each slot when computing the voyage, and this is an export of the ordered list of crew for each skill.

**Comment by pim69** [comment]
Thanks again paulbilnoski.

While the export runs slowly for me so it's not a fast solution, but it does give me exactly what I'm looking for so thanks very much.  I missed that there were 2 csv's exported the first time and only saved one (not the one I needed obviously).  Interestingly that export is affected by if you select to include frozen or crew on shuttles, which could even add an interesting second element of finding out weakest "B" voyage crew when doing a specific faction event.
