### ISSUE TITLE
Voyage wont calculate

### ISSUE THREAD

**Issue by Anubis07** [IAmPicard/StarTrekTimelinesSpreadsheet#174]
Hi there i have been using your browser tool. Everything works fine apart form i can not get the voyage part to work on my main account, It wont start calculating which crew would be best. I have tried altering the search depth all the way down to 1 but still no response. How ever if i use my second account it works perfectly. I dont know if this has anything to do with i only have 100+ crew on that account and my main account is over 200+

**Comment by IAmPicard** [comment]
Is it the same browser / OS for your second account?
Are you using English as the in-game language option?

**Comment by Anubis07** [comment]
Yeah it is the same browser and os (Windows) for both. Tried it on my iphone and ipad but no joy. Yes English is the in game Language. Have tried using other browsers but still with the same result. I can however use the App no problem at all. I have made sure i have signed out of the App as well. The browser would be a handy option when i dont have access to my pc for sending out voyages.

**Comment by auto2000** [comment]
Have had the same problem with browser version on an established account with 265 crew. Everything works except calculating voyage crew. Works fine on the tool in Windows.

**Comment by IAmPicard** [comment]
I have 447 crew and it works correctly for me; whatever is going on is probably not a function of the number of crew.

Hmm... I wonder if it would be possible to look in the dev tools (F12 for most desktop browsers) and see if there are any errors that show up when trying to hit Calculate. It's a long shot since the error messages will be pretty cryptic, but there may be something in there that pops out as interesting.

**Comment by IAmPicard** [comment]
Is your OS language set to English, or something else? Can you try exporting the crew from an account that has this issue? Export -> CSV from the crew list (either online or in the app) would work.

I can't really find much about this error message, it appears that the string representation is non-standard (UTF-16) and the WebAssembly code chokes on it. The only thing that comes to mind is maybe a crew name with non-ASCII characters, or perhaps an OS setting that somehow affects the way JavaScript encodes strings.

**Comment by auto2000** [comment]
Yea, it's in English.

[My Crew.zip](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/files/2454268/My.Crew.zip)

**Comment by IAmPicard** [comment]
Thank you for that. I was able to track down the problem to "Zhian’tara Odo". Specifically, the apostrophe they use to separate Zhian and tara is not a normal quote character, but some sort of weird unicode variant that happens to look like a quote.

I'm looking for a generic solution now, but will at least hardcode this crew's name if I can't find a generic fix.

**Comment by IAmPicard** [comment]
Ok, I pushed a tentative fix to the website. Can you guys give it a try and let me know if you can calculate correctly now?

Your browser may be caching stuff, so try a force reload first (Ctrl+F5 usually does it).

**Comment by IAmPicard** [comment]
Cool, thanks.

**Comment by Anubis07** [comment]
Fantastic work its working perfectly now. Many thanks for your efforts very much appreciated
