### ISSUE TITLE
Crash when trying to calculate voyage crew on 0.8

### ISSUE THREAD

**Issue by hackel** [IAmPicard/StarTrekTimelinesSpreadsheet#175]
**Describe the bug**
Since ugrading to 0.8, whenever I try to calculate crew for a voyage, Electron crashes.
Version: v0.8.0
Node: v10.11.0
Ubuntu 18.04

**To Reproduce**
1. Launch STTS with npm run build && prod
2. Go to Voyage
3. Click on Calculate
4. Electron dies with this entirely unhelpful error message:
```
symbol lookup error: ~/src/StarTrekTimelinesSpreadsheet/native/build/Release/NativeExtension.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
```
**Expected behavior**
Crew calculates like normal.

**Additional context**
I had some trouble installing 8.0.  I was unable to install the npm packages with the current package-lock.json.  It kept giving me this error:
```
npm ERR! enoent ENOENT: no such file or directory, rename '~/src/StarTrekTimelinesSpreadsheet/node_modules/.staging/sttapi-de06cbd3/node_modules/@types/node' -> '~/src/StarTrekTimelinesSpreadsheet/node_modules/.staging/@types/node-c38f35bb'
```
Removing and regenerating the package-lock.json file got around this issue.
If I run `npm run dev`, I get a blank Electron window with "Cannot GET /index.html".  The production build is working, though, aside from the voyage crash.

I had previously built 9725fb8 and everything was working great.

**Comment by IAmPicard** [comment]
You need to rebuild the native module whenever the electron version changes:
```
cd native
npm install
cd..
./node_modules/.bin/electron-rebuild
npm run dev
```

**Comment by hackel** [comment]
Thanks, I should have mentioned that I cloned a fresh copy and built it from scratch, so I didn't think I had to do that.  After following your instructions, dev still does not work, but the prod build is calculating without crashing.  Not sure what's going on there, as the dev used to work just fine.
