### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dharkus** [IAmPicard/StarTrekTimelinesSpreadsheet#177]
**Describe the bug**
On the voyage page, the dilmena system has duplicated all the dilemna choices quite a lot, enough to fill 4pgs of scrolling down on a 1080p monitor - there is 3 differents sets of choices that are duplicated - likely the 3 dilemnas i've had this voyage

**To Reproduce**
6hr+ voyage where I chose the dilemnas in game

**Screenshots**
![image](https://user-images.githubusercontent.com/6401304/46223017-01ccdf00-c34a-11e8-9859-e77bd41798be.png)

**Additional context**
Tool version: **0.8.0**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
Fixed in master; deployed to the web version; desktop 0.8.1 will have it as well.
