### ISSUE TITLE
Warp Missions Not Displaying Accurate "Availability"

### ISSUE THREAD

**Issue by KarmaPoliceT2** [IAmPicard/StarTrekTimelinesSpreadsheet#180]
**Describe the bug**
Some warp missions are not working, others are working... Turns out this is because I haven't unlocked the missions that aren't working... there should probably some indicator of this considering that STTS does know what missions i have and haven't unlocked... 

**To Reproduce**
This screenshot shows all missions except "The Toss" available to me
![image](https://user-images.githubusercontent.com/5385821/46303226-21d5eb80-c560-11e8-8da1-6b32b9886cf8.png)

In reality, some of these should be greyed out (not sure why "The Toss" is to be honest) as here is what I see in game:
![image](https://user-images.githubusercontent.com/5385821/46303269-4205aa80-c560-11e8-829c-25e353af60fd.png)

On further exploration, STTS seems to think I have completed all nodes of The Rings of Time, but I have really only completed it on Normal difficulty... I would have thought it would not mark a mission complete until all difficulties were completed:
![image](https://user-images.githubusercontent.com/5385821/46303612-28b12e00-c561-11e8-914b-e286befb3b5c.png)

It still seems that it should grey out missions based on difficulty+mission instead of just "mission"... but then so should the missions module in terms of "marking complete"

**Expected behavior**
Would expect the missions not unlocked to warping would appear greyed out

**Screenshots**
see above

**Additional context**
Tool version: **0.8.0-web**
Operating system: **Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36**

**Comment by KarmaPoliceT2** [comment]
Hmm it started working again, but again diff mission... seems it is the Baited Hook mission which i can't run (and a couple others though i don't recall others i clicked)... but some i am clicking work fine as well... so must be something specific to those missions

**Comment by KarmaPoliceT2** [comment]
Starting a running list of failing missions in the original bug report.

**Comment by KarmaPoliceT2** [comment]
bah, i figured it out... the missions I'm trying to run that aren't working are because I don't have them unlocked in the game... I figured they would show as greyed out like "The Toss" in this SS: but in fact they don't grey out just because they aren't available to me... maybe this should become a feature request:
![image](https://user-images.githubusercontent.com/5385821/46303180-fc48e200-c55f-11e8-8866-c0990f8cee5f.png)

**Comment by SodPen1** [comment]
Piggybacking here to mirror the feedback.  Have the same behavior in my application and find it somewhat inconvenient to a point where I would elevate it to a priority issue for addressing going forward.  When it works, it works fabulously.  Just need to correctly list which missions are and are not viably "warpable" based on actual mission status across all three difficulties and successful rare reward collections for each.
