### ISSUE TITLE
New build 0.8.0 - Failed to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by beertastic** [IAmPicard/StarTrekTimelinesSpreadsheet#181]
**Describe the bug**
Won't install on Ubuntu 18.04

**To Reproduce**
Deleting old version and starting over following the same instructions, I get the following messages.

> startrektimelinestool@0.8.0 dev /home/tris/code/StarTrekTimelinesSpreadsheet
> webpack-dev-server --mode development --hot --host 0.0.0.0 --config=./webpack.dev.electron.config.js

sh: 1: webpack-dev-server: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! startrektimelinestool@0.8.0 dev: `webpack-dev-server --mode development --hot --host 0.0.0.0 --config=./webpack.dev.electron.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the startrektimelinestool@0.8.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Expected behavior**
Loads.

**Additional context**
Log file

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle startrektimelinestool@0.8.0~predev: startrektimelinestool@0.8.0
6 info lifecycle startrektimelinestool@0.8.0~dev: startrektimelinestool@0.8.0
7 verbose lifecycle startrektimelinestool@0.8.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle startrektimelinestool@0.8.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tris/code/StarTrekTimelinesSpreadsheet/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/tris/.composer/vendor/bin:/home/tris/.config/composer/vendor/bin
9 verbose lifecycle startrektimelinestool@0.8.0~dev: CWD: /home/tris/code/StarTrekTimelinesSpreadsheet
10 silly lifecycle startrektimelinestool@0.8.0~dev: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --mode development --hot --host 0.0.0.0 --config=./webpack.dev.electron.config.js' ]
11 info lifecycle startrektimelinestool@0.8.0~dev: Failed to exec dev script
12 verbose stack Error: startrektimelinestool@0.8.0 dev: `webpack-dev-server --mode development --hot --host 0.0.0.0 --config=./webpack.dev.electron.config.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid startrektimelinestool@0.8.0
14 verbose cwd /home/tris/code/StarTrekTimelinesSpreadsheet
15 verbose Linux 4.15.0-34-generic
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
17 verbose node v10.10.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error startrektimelinestool@0.8.0 dev: `webpack-dev-server --mode development --hot --host 0.0.0.0 --config=./webpack.dev.electron.config.js`
23 error spawn ENOENT
24 error Failed at the startrektimelinestool@0.8.0 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by beertastic** [comment]
Ah, the node_modules folder is empty.. and the install is trying to rename a folder called .staging.. that doesn't exist. If that helps?

**Comment by IAmPicard** [comment]
FWIW I’ve seen something similar on Windows after upgrading npm. I fixed it by running ‘npm install -only:dev’. I’ll follow up to see what changed in npm and what I have to change in the project.

**Comment by IAmPicard** [comment]
I might need to switch to yarn or something like that; for now, calling this fixed (usually removing node_modules and reinstalling as paul suggests fixes it for me).
