### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Capt-Who** [IAmPicard/StarTrekTimelinesSpreadsheet#183]
**Describe the bug**
On my voyages for star trek timelines I get more choices then necessary, around 26 or more
![multiple choices](https://user-images.githubusercontent.com/43762092/46310985-172a4f00-c57e-11e8-93e1-d826c40a3eff.JPG)
. 

**To Reproduce**
Steps to reproduce the behavior: This happens at the 2, 4 or 6 hour mark of the voyage

**Expected behavior**
I should only get 3-4 choices

**Screenshots**
See above

**Additional context**
Tool version: **0.8.0-web**
Operating system: **Chrome/69.0.3497.100 **

**Comment by IAmPicard** [comment]
Investigation notes: in VoyageTools.ts, function loadVoyage, at mergeDeep we're looking at elements ids ; do dilemmas have ids or other unique identifiers?
As a hack, we could clear out the dilemma before loading - need to test when I actually have an unresolved dilemma.
