### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by edjusted** [IAmPicard/StarTrekTimelinesSpreadsheet#185]
**Describe the bug**
Doesn't run in Mac. At launch, it shows this error:
An error occured while loading data!

Try restarting the application, if the error persists, please log a bug. Details: Error: Network error, status 400, reply {"message":"VERSION_ERROR_FORCE_UPATE 6.0.0"}

**To Reproduce**
launch the program

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.5**
Operating system: **darwin x64 (18.0.0)**

Error details: Error: Network error; status 400; reply {"message":"VERSION_ERROR_FORCE_UPDATE 6.0.0"}.

**Comment by IAmPicard** [comment]
That is an old version which can no longer connect to DB's servers.

Unfortunately, I don't have a mac machine available to make a new build. If you're somewhat technical and want to try building it yourself, see some [details here](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet#development-environment).

**Comment by IAmPicard** [comment]
I still couldn't find a mac machine to borrow. Consider using the [web version](https://iampicard.com/) instead, which has almost the same functionality as the desktop version.
