### ISSUE TITLE
Voyage tab is white screen - must restart app

### ISSUE THREAD

**Issue by auto2000** [IAmPicard/StarTrekTimelinesSpreadsheet#190]
When opening the voyage tab and switching to the recommendations screen, the screen becomes blank and there are no buttons to interact with. Restart is required. Other user with same problem: https://bit.ly/2ymoaMa

This is what appears when clicking Voyage tab - https://i.imgur.com/AdnLnJE.png

And when clicking on "Switch to recommendations" - https://i.imgur.com/cYePOGh.png

v0.8.0, but problem has occurred in previous versions. Behavior only exists in 1 of 3 accounts.

**Comment by IAmPicard** [comment]
I uploaded a debug build of the tool to the latest release; if you have a chance, can you download that and try to repro the problem?

Before repro, open the developer tools by clicking on your Captain name, then on the button that looks like a bug. This will open a pane inside the window, similar to the Chrome devtools if you ever used that.

Go to the console tab in that window, repro the problem, and let me know if you see any errors show up in the console. It should look like this:
![image](https://user-images.githubusercontent.com/31076775/46576632-796ebf80-c983-11e8-953e-8737498660a4.png)

**Comment by auto2000** [comment]
![voyage](https://user-images.githubusercontent.com/43791078/46578839-9056f580-ca07-11e8-8e60-54e6600a598e.png)

**Comment by IAmPicard** [comment]
I believe e87dc0f471ced0d0ad1cf38c666988eec68f1822 will fix this issue. It probably applies only to very new accounts that only have the Constellation class (free) ship, and no others.
