### ISSUE TITLE
Crash when loading last crew page

### ISSUE THREAD

**Issue by ChewableCPP** [IAmPicard/StarTrekTimelinesSpreadsheet#197]
When I attempt to load the 11th (last) page of the crew tab, the tool goes blank and this is in the console:

TypeError: Cannot read property 'original' of undefined
    at getTrProps (bundle.js:35)
    at et (bundle.js:35)
    at Array.map (<anonymous>)
    at nt (bundle.js:35)
    at t.value (bundle.js:35)
    at Xr (bundle.js:116)
    at Yr (bundle.js:116)
    at Jr (bundle.js:116)
    at Io (bundle.js:116)
    at Oo (bundle.js:116)

This can be reproduced with a filter as well, as long as there is more than one page to begin with.

**Comment by IAmPicard** [comment]
Would you be able to try the desktop tool, might have better callstacks?

**Comment by ChewableCPP** [comment]
That actually was the desktop tool :S

Seems trivial to repro though? I assume most people just haven't run into it because there's not much reason to actually flip the crew pages rather than filtering or exporting.

**Comment by PhantumPhysics** [comment]
I noticed this also on the desktop version.  I was in a rush and just sorted the opposite way to get the last page first though.

**Comment by IAmPicard** [comment]
It would be great if you could build the tool locally, or install the previous release's debug build for a better callstack. I can't repro the problem, nor can I see how this can possibly fail by reading the code:
`opacity: (r && r.original && r.original.isExternal) ? "0.5" : "inherit"` ; it doesn't make sense to evaluate r.original if r is undefined. But who knows, JavaScript is weird.

**Comment by ChewableCPP** [comment]
It seems to be fixed in 0.81 somehow. Confirmed still broken in 0.80 with my current profile.

**Comment by IAmPicard** [comment]
It was probably fixed with dbdaf96254ef120100940ba9e202b2b61321a8ec . @PhantumPhysics, are you seeing this on 0.8.1 or 0.8.0 ?

**Comment by PhantumPhysics** [comment]
It was in 8.0 I think.  Sorry I missed the notifications about this thread

**Comment by IAmPicard** [comment]
I'll call this fixed.
