### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Stepwisecliche** [IAmPicard/StarTrekTimelinesSpreadsheet#2]
It's asking for login information now. Due to establishing an account through Facebook, account details are difficult to get. I tinkered around with it for an hour and it doesn't seem to use my Facebook e-mail or accept my Facebook password. Is there a way to still use token?

**Comment by IAmPicard** [comment]
Hi,
I added the username / password login to make it easier to use for most players. Didn't realize you can actually play the game without an username / password; I guess this can happen on other platforms as well (like google play or apple gamecenter for Android/iOS).

To get you unblocked while I'm adding an UI option for it, you can manually edit the configuration file. For example:

`notepad %APPDATA%\startrektimelinestool\storage\userConfig.json`

Save the file with this content:

`{
   "accessToken":"_your_access_token_here_",
   "autoLogin":true
}`

Let me know if this worked.

**Comment by IAmPicard** [comment]
After looking a bit into how it's done I actually ended up implementing Facebook login in the tool itself. Check it out in the [0.4.2 release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.4.2)!

**Comment by Stepwisecliche** [comment]
Work great!
