### ISSUE TITLE
crew excel export not working

### ISSUE THREAD

**Issue by Gryphonsdream** [IAmPicard/StarTrekTimelinesSpreadsheet#202]
i found the same issue on the online version also.
csv works, but doesn't include all data from excel and is in different column order

**Comment by IAmPicard** [comment]
Sorry for not testing this. I fixed it with 06d6c4fe2ebf8c9ba4641aa3f7ee82931a47d040 . Will be included in the next release.

I'm hoping to do a web release soon (tomorrow), but it'll take a while for the next desktop tool version.

**Comment by CommodoreMendy** [comment]
I'm still having the same issue.

**Comment by IAmPicard** [comment]
In the web version?

**Comment by CommodoreMendy** [comment]
Yes, the web version.  Is there a version for android?  I only know of this version.

**Comment by IAmPicard** [comment]
By web version, I mean the website itself at [iampicard.com](https://iampicard.com/) - I have a fully functional version of the tool that you can run in your browser. I just tested Excel export there and it works.

The fix will be included in the desktop version as well in the next release.

**Comment by IAmPicard** [comment]
[Release 0.8.2](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.8.2) is out and it includes this fix.
