### ISSUE TITLE
New Gauntlet no longer shows show player character stats

### ISSUE THREAD

**Issue by PhantumPhysics** [IAmPicard/StarTrekTimelinesSpreadsheet#203]
The latest update has improved the gauntlet, but the player characters at the top no longer show their stats which I found helpful.

I would like to see the stats back, it was really helpful to pick which fight to take to see all the stats the character had to consider future battles also.  Not such a big deal but I found it helpful.

**Comment by Gryphonsdream** [comment]
yeah, i noticed this also, :-(
would also be nice to know how long to crew refresh on gauntlet screen when re loading again
but only minor thing to me as i play in both app and game at the same time depending on what i am doing. not like i can do a ship battle in the app, just have to remember not to load the app when battling 
LOL.

**Comment by PhantumPhysics** [comment]
Thanks heaps
