### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by kaleksic** [IAmPicard/StarTrekTimelinesSpreadsheet#205]
**Describe the bug**
The event crew don't show

**Screenshots**
![screen shot 2018-10-25 at 09 23 29](https://user-images.githubusercontent.com/35513673/47503348-dac5d800-d837-11e8-9d74-4aae6b961057.png)

**Additional context**
Tool version: **0.8.0-web**
Operating system: **Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36**

**Comment by PhantumPhysics** [comment]
I think this is because this is a skirmish event and the crew on the voyage can still be in ship battles for skirmishes.  Therefore it is correct that no crew are held back from the voyage

**Comment by IAmPicard** [comment]
Yes, correct; I don't fill in skirmish events because you can still use the crew on voyages while you're using them in the event. I can fix the wording there a bit to reflect it.

**Comment by kaleksic** [comment]
It did dawn on me later. 
I will not file any more bug reports before *at least* the second coffee. ;)
