### ISSUE TITLE
Can we see Faction Center's Store items on program

### ISSUE THREAD

**Issue by gunescaptain** [IAmPicard/StarTrekTimelinesSpreadsheet#206]
Thank you, Great work^^

**Comment by IAmPicard** [comment]
Yes, I was just thinking about it the other day, I often find faction-only items like ancient films in the faction stores for measly amounts like 50 merits, totally worth it.

**Comment by IAmPicard** [comment]
You can see this live in the [web tool](https://iampicard.com) (in the overflow '...' menu choose Factions). There are a few more tweaks to get it release-quality, but basic functionality is there.

**Comment by IAmPicard** [comment]
[Release 0.8.2](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.8.2) is out and it includes this feature. There's still some work left to do, but basic functionality is there.

**Comment by gunescaptain** [comment]
Thank you :) can we see which one faction item we need 👍🏻

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
