### ISSUE TITLE
Mission Completion Not Updating

### ISSUE THREAD

**Issue by billyhtchcoc** [IAmPicard/StarTrekTimelinesSpreadsheet#211]
**Describe the bug**
The information under the "Missions" section of the "Tools and Recommendations" tab updates the number of stars achieved in the overarching Episode is correct, but on the individual missions within the episode, it doesn't update properly, even after hitting the refresh on the Captain page and/or logging out.  

It appears to be only showing the information as of the very first time you logged into the tool (I have used the suggestions provided by the tool to finish a number of Cadet Missions over the last few days with all the other tools/platforms closed except a single client at a time used for playing the game) and doesn't update the missions properly.

As a result, when you are filtering to "show only unfinished missions", it gives out of date information

**To Reproduce**
1. Go to 'Tools and Recommendations > Missions'
2. Click on the settings drop down to select the 'show only unfinished missions' box.
3. Click on the drop down and scroll down to select a mission.
4. Read the suggested personnel to complete the mission and make note of them.
5. Close the tool
6. Open the client to play the game.
7. Perform the mission at the epic difficulty and achieve full stars for it.
8. Close the game client
9. Reopen the tool, log in (if necessary), and hit 'Refresh' (just in case).
10.  Perform Steps 1-2.  
11.  If the mission is still showing in the drop down, this is where the bug is.  

**Expected behavior**
The tool should update the 'show only unfinished missions' list to actually show that the mission has now been finished.  Additionally, when you go into the mission it should show that you've got 3/3 of the difficulty level completed.

**Comment by IAmPicard** [comment]
Can you try uninstalling the tool, then deleting the "%APPDATA%\Star Trek Timelines Crew Management" folder and reinstalling it?

It will take a long time to reload all the assets again, but I'm curious if this fixes it.

I suspect DB changed the definition of "mission complete on the backend which confuses the tool into not reloading the mission data.

**Comment by billyhtchcoc** [comment]
This seems to have fixed the issue.
