### ISSUE TITLE
Bug: Frozen Crew Skill Values Are Incorrect

### ISSUE THREAD

**Issue by eljay69** [IAmPicard/StarTrekTimelinesSpreadsheet#215]
**Describe the bug**
I had to revert to the 8.0 version because I depend on the Excel export file for inventory and crew maintenance, so I don't know if this issue exists in 8.1, but I do not see it listed here so it probably is.

It appears that the skill values retrieved by the app (for both the in-app crew page and the exported Excel file) are the skill values that were current at the time the crew was frozen.  Any starbase or collection skill boosts after that time are not accounted for.

In the game itself, viewing frozen crew in the Cryostasis Vault displays the correct values based on the current total skill boosts.

**To Reproduce**
1. Open the app, navigate to the Crew page and view the skill values of a character frozen before your current skill boost values were attained.
2. Also export the crew data to an Excel file.
3. View this character in-game in the Cryostasis Vault and see that the values are greater than those on the Crew page or the Excel file.

**Expected behavior**
I expect current and accurate values for crew skills.

**Screenshots**
Two screenshots attached.

**Additional context**
None

**Comment by IAmPicard** [comment]
This was actually fixed in 0.8.1 somewhat with 744bf3272a905f9f6889a325472e7b825db068ff.

If DB changes the actual base skill values, you need to force reloading the data; you can do that by uninstalling the tool, then deleting the "%APPDATA%\Star Trek Timelines Crew Management" folder and reinstalling it.

**Comment by eljay69** [comment]
Thanx for the response and extra info.  I'll have to wait for 8.2 because of my dependence on the Excel export file.  Hmmm, just realized I may not be able to wait when STT 6.1 is forced.

Regardless, the app is indispensable and has made playing the game much more enjoyable (and tolerable).  My appreciation to you and the others who have contributed.

- eljay

**Comment by IAmPicard** [comment]
[0.8.2](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.8.2) is out and it includes the Excel bug fix. Give that a try.

**Comment by eljay69** [comment]
Oh, that is fantastic.  Thank you very much.  I will install it first thing tomorrow morning and let you know how it goes.

Cheers,
eljay

**Comment by eljay69** [comment]
Perfecto, Maestro.  Everywhere, campers are happy.

Double cheers,
eljay
