### ISSUE TITLE
Dark mode won't stay enabled

### ISSUE THREAD

**Issue by DjZiio** [IAmPicard/StarTrekTimelinesSpreadsheet#23]
It might be an actual feature not a bug but I can't get dark mode to stay enabled to always be on. The blinding white backgroud destroys my eyes early in the morning and everything on my computer is modded to be grey or black. If its a feature or impossible to code I understand. I LOVE the new voyage feature but it took  me a while to figure it out. If you have to be logged out of the game, like I'm assuming, having a tool tip or info box would be helpful. This is hands down the best tool for any game I play!

**Comment by IAmPicard** [comment]
I never implemented saving the dark mode state, but totally feel your pain. I'll add that to the TODO.

Yes, the "start voyage" button was added in a hurry (you get no feedback that something happened for example). I'll work on improving that.

You shouldn't need to be logged out of the game in theory. But the tool also doesn't refresh stuff before starting a voyage. So if you ended / started some shuttles or something to that effect, it may be a good idea to restart the tool for it to get up-to-date status of crew.

**Comment by IAmPicard** [comment]
This was fixed with release [0.6.7](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.6.7), we now persist the dark mode setting. Closing.
