### ISSUE TITLE
Bug report: Voyages not working

### ISSUE THREAD

**Issue by tank8** [IAmPicard/StarTrekTimelinesSpreadsheet#230]
**Describe the bug**
No response after clicking the calculate button.

**To Reproduce**
Steps to reproduce the behavior: click the calculate button

**Expected behavior**
Processing message/loading circle animation

**Screenshots**

**Additional context**
Tool version: **0.8.2-web**
Operating system: **Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36**

**Comment by IAmPicard** [comment]
Does it still repro if you reduce the depth to 5, or 4? Are you using a very old / slow computer?

Can you open the dev tools (F12 on most browsers) and see if there are any errors (in red) in the console tab of the dev tools pane?

**Comment by tank8** [comment]
Looks like it works with a lower depth. I miss the old layout though.

**Comment by IAmPicard** [comment]
I'm between a rock and a hard place... I'm not a frontend dev which makes it even more difficult. Basically, I need to have an UX / interface that works both on desktop (large screen) and on mobile (tiny screen, fat fingers).
