### ISSUE TITLE
Crew member stuck in dismiss folder with no expiration time after using dismiss dupes. Crew slots misaligned by 1. 

### ISSUE THREAD

**Issue by STTRR9OF7** [IAmPicard/StarTrekTimelinesSpreadsheet#246]
**Describe the bug**
i used the dismiss dupes function to dimiss melora she is stuck in the dismiss folder with no expiration time. I cannot recall her gives error "crew has no expiration time" nor dismiss her. this has also given me 219/220 slots the empty slot is taken up by melora even though she is not active. I cannot use the slot for anything else until i am able to dismiss melora. I have used the dupes button a few times and had no issues. been like this for a week now. darent contact db obviously. excellent program by the way. 
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by IAmPicard** [comment]
This is a bug on DB's side. It happens sometimes, regardless of whether you use the tool or the game itself to dismiss. You can find reports on the forums, like [this one](https://forum.disruptorbeam.com/stt/discussion/10878/crew-slot-issue-unusable-crew-slots#latest) . You'll need to contact DB support to take care of this on the server side, there's nothing I can do from the tool.

**Comment by STTRR9OF7** [comment]
Many thanks for the reply. I will open a ticket with DB.
