### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Afrim124** [IAmPicard/StarTrekTimelinesSpreadsheet#248]
**Describe the bug**
I got the error: Try restarting the application; if the error persists, please log a bug. Details: Error: Network error; status 400; reply {"message":"VERSION_ERROR_FORCE_UPDATE 6.1.0"}

**To Reproduce**
Steps to reproduce the behavior: Start the application.

**Expected behavior**
Maybe I need the updated version, but where to get it?

**Screenshots**

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

Error details: Error: Network error; status 400; reply {"message":"VERSION_ERROR_FORCE_UPDATE 6.1.0"}.

**Comment by IAmPicard** [comment]
It looks like you're using a very old version of the tool. The latest is [0.8.2](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.8.2).
