### ISSUE TITLE
TypeError: "s.a.playerData.motd.text is undefined" > White screen

### ISSUE THREAD

**Issue by Iriadel** [IAmPicard/StarTrekTimelinesSpreadsheet#259]
I can't use the windows app nor the online tool anymore. I'm getting a white screen on both.

![Here is a screenshot of the error and its backtrace on firefox](https://user-images.githubusercontent.com/46281239/50561005-a9b9c600-0d06-11e9-8c2f-578c96932c1a.JPG)

The last things I did before this problem were :
- Launching a new gauntlet in the app and having 12 consecutive wins (in the app too)
- Leveling "Boothby Groundkeeper" to level 100 with no objects yet in the game (I've frozen him since then, nothing changed)
- Doing my first cadet mission of the day in the game
- Buying  a merit pack in the game

**Comment by PsionStorm** [comment]
Confirming this issue on both standard, beta, and desktop client (though my screen is dark blue, I assume because of my color choice).

**Comment by Iriadel** [comment]
I think it's related since it looks like the same step, but it's a different error message. I checked again, I'm still having the "undefined" message, not the "trim" message.

**Comment by paulbert** [comment]
It looks like the same error.  I get the trim error message in the web client, but it traces back to the same line
```
__html: s.a.playerData.motd.text.trim().replace(/(?:\r\n|\r|\n)/g, "<br />")
```

That is showing the "Message of the day" text in the app, but checking the game there is no message of the day right now so that property is undefined.

**Comment by Iriadel** [comment]
The survey added a brand new message of the day, so the app is UP again. But this is a bug that should be fixed, it will probably go down again tomorrow.

**Comment by IAmPicard** [comment]
Thank you for the report and investigation. I'll try to push a fix for this soon.
