### ISSUE TITLE
minimal crew complement needed for cadet challenges needs overhaul

### ISSUE THREAD

**Issue by dharkus** [IAmPicard/StarTrekTimelinesSpreadsheet#26]
currently it shows loads of crew which could be frozen or airlocked (not limited to cadets, separate section needed for 4*+?) and doesn't give any reason why they're not needed, same goes for crew which needs to be unfrozen. It appears to give the full list for 2*s that need to be used to get all stars on cadet missions, and maybe same for all other missions, but with warp 1 available for all, and critting not needed on cadets, this list should be a lot smaller. Also in the 1st list are crew which have already been dismissed (in the last 4hrs) (dismissed crew are also in the duplicates, which seems unnecessary).

**Comment by IAmPicard** [comment]
This feature was extremely outdated and borderline unusable. Some of its functionality is superseded by the missions tab; I just removed it to avoid confusing new app users.
