### ISSUE TITLE
Blank screen after completing load on either app or website

### ISSUE THREAD

**Issue by AmorgenBurke** [IAmPicard/StarTrekTimelinesSpreadsheet#260]
**Describe the bug**
The app or website will show the normal loading messages, but when it normally would finish and give you the options and summary (the home page), instead the page goes completely blank.

**To Reproduce**
1. Go to either the website (I use Chrome as my browser) or app (I'm running Windows 10).
2. Watch the loading messages (Loading player data, mission success, etc.)
3. The loading messages disappear (no consistent final message)
4. The screen is now blank and nothing further happens in either the website or app.

**Expected behavior**
When the loading messages finish, normally the home page appears with menus across the top and a summary of what you have running or have used.

**Screenshots**
A blank screenshot would not particularly help in diagnosing the issue.

**Additional context**
This issue started very recently.  I have not had this issue in the past and have been using the app for a few months.

**Comment by Iriadel** [comment]
The survey added a brand new message of the day, so the app is UP again. But this is a bug that should be fixed, it will probably go down again tomorrow.
