### ISSUE TITLE
tooltips on crew page for the symbols

### ISSUE THREAD

**Issue by dharkus** [IAmPicard/StarTrekTimelinesSpreadsheet#28]
the previous version had a snowflake to indicate cryostasis, current version has a cloud, if i'd not seen the snowflake i'd have no idea what that was, the bin (not easy to tell what it is) and balloons aren't at all obvious what they signify, either better symbols should be used or tooltips when you mouseover them could solve this

**Comment by IAmPicard** [comment]
This is finally implemented in [release 0.7.7](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.7); the various icons in the crew row will display a tooltip when hovered.
