### ISSUE TITLE
Network Error:type error:cannot read prope...

### ISSUE THREAD

**Issue by Kennyd730** [IAmPicard/StarTrekTimelinesSpreadsheet#3]
I have used this for about 3 weeks with no problem. Recently I have not been able to log in.
This is the error i get when putting in my login/password now is.

Network Error:type error:cannot read prope...

**Comment by IAmPicard** [comment]
Ah, yes... it looks like DB revved the client version to 3.0.1 and the tool reports itself as a client version 3.0.0 which they no longer allow to connect on the server.

I'll publish an updated release in a few minutes.

**Comment by IAmPicard** [comment]
See new release [here](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.5.7). Let me know if it fixes the issue for you.

**Comment by janelletin** [comment]
That fixes the issue for me. Thanks for the quick fix.

**Comment by Kennyd730** [comment]
Yes sir! Thank you not only for the quick response and fix! And most of all thank you for the Crew management program!
