### ISSUE TITLE
Please build the macOS version

### ISSUE THREAD

**Issue by jouhtis** [IAmPicard/StarTrekTimelinesSpreadsheet#32]
It would be lovely to have macOS version of this software as well.

**Comment by IAmPicard** [comment]
Unfortunately I don’t own a Mac machine, and you can’t cross-compile from a Windows box - Apple’ rules.

**Comment by jouhtis** [comment]
Oh, i did see you build one earlier so i assumed it would be just one checkbox to build the mac package as well. Oh well, have to try to compile my own version then :)

**Comment by IAmPicard** [comment]
Let me know if you have issues. There are some getting started instructions in the readme.

I tried in once before we had native code. The voyage recommendations are implemnted in C++ now which you can’t compile on Windows.

**Comment by jouhtis** [comment]
issues that i had were:

1. had to install npm module ajv manually
2. had to add few extra compiler flags to native/binding.gyp file:
`
			"xcode_settings": {
				"OTHER_CFLAGS": [
					"-std=gnu++14"
				]
			}
`
3. with these modifications, the build inside dmg package doesnt want to open, just gives blank white page. npm run dev still runs fine.

**Comment by IAmPicard** [comment]
I managed to borrow a Mac machine from a colleague today. Checked in a fix for the native module, and added a .dmg to the release. Don't have a different Mac machine to try it on, so please let me know if it works.

**Comment by technophile77** [comment]
Runs fine on Mac for me.

**Comment by jouhtis** [comment]
Yeah, now it runs fine, thank you :)

**Comment by IAmPicard** [comment]
I'll close this for now. Proven doable, but since I don't have permanent access to a mac machine, future releases will most likely not have mac installers.

**Comment by yancancook** [comment]
I was able to build, but am stuck on screen "Caching crew images... (0/1085)".  Anyone who has it working on mac have any suggestions?

**Comment by IAmPicard** [comment]
Are there any errors in the debug pane, or the terminal?

**Comment by yancancook** [comment]
Yes, after failure, I attempted a manual build of AssetParser and ajv, but that produced same log result:


bundle.js:158747 [HMR] Waiting for update signal from WDS...

bundle.js:87079 Download the React DevTools for a better development experience: https://fb.me/react-devtools

bundle.js:16357 Warning: Can't call forceUpdate on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the App component.

printWarning @ bundle.js:16357
/Users/xxxxxxxx/Documents/GitHub/StarTrekTimelinesSpreadsheet/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Node.js Integration with Remote Content) This renderer process has Node.js integration enabled and attempted to load remote content. This exposes users of this app to severe security risks.

For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.
.
.
.
[WDS] Hot Module Replacement enabled.
STTApi.js:241 Loaded 549 crew avatars
STTApi.js:232 Loaded server config
STTApi.js:253 Loaded platform config
STTApi.js:290 Loaded 39 ship schematics
STTApi.js:262 Loaded player data
STTApi.js:314 Loaded fleet member info
STTApi.js:327 Loaded fleet data
STTApi.js:340 Loaded starbase data

(unknown) Uncaught ReferenceError: Buffer is not defined
    at Parser.eval [as compiled] (eval at ./node_modules/binary-parser/lib/binary_parser.js.Parser.compile (assetWorker.js:4448), <anonymous>:3:1)
    at Parser../node_modules/binary-parser/lib/binary_parser.js.Parser.parse (assetWorker.js:4499)
    at Object.parseAssetBundle (assetWorker.js:3957)
    at parseAndConvertToPng (assetWorker.js:4122)
    at assetWorker.js:4142

**Comment by IAmPicard** [comment]
That buffer not defined error looks suspicious; it suggest AssetParser is not the latest version for some reason.
Try running "git pull origin master" in STTApi\AssetParser\, followed by npm install, then do the same in SttApi\

**Comment by yancancook** [comment]
Good call!  It works now.  Not sure how that delta happened since I cloned yesterday.  The pull updated binary_parser & context.  Thanks so much!
