### ISSUE TITLE
Gauntlet: Show Merits

### ISSUE THREAD

**Issue by dewittified** [IAmPicard/StarTrekTimelinesSpreadsheet#34]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
To have Merits total be always on. Right now it only shows after you use them to refresh new opponents.

**Additional context**
Tool version: **0.6.8**
Operating system: **win32 x64 (10.0.16299)**
![image](https://user-images.githubusercontent.com/36380490/39669445-17faeb8c-50a9-11e8-97fc-be369f356e84.png)

**Comment by IAmPicard** [comment]
This is fixed in the [0.7.0 release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.0).
