### ISSUE TITLE
Gauntlet History Log

### ISSUE THREAD

**Issue by peachtreerex** [IAmPicard/StarTrekTimelinesSpreadsheet#36]
**Is your feature request related to a problem? Please describe.**
I would like to be able to keep a history of my gauntlet successes/failures

**Describe the solution you'd like**
I would like to have the option of turning on a CSV output log for my individual gauntlet matchups

**Describe alternatives you've considered**
The best alternative I can think of is manually recording matches which is very tiresome and work intensive.

**Additional context**
Additionally, I am hoping to pool my results with others to definitively show if the gauntlet is (or is not) biased in any particular way.

The following data fields would be most helpful:

- Date/time the match was run
- Current streak status
- Characters used (Name, Crit%, Roll Ranges)
- Skills being tested (Dip/Cmd/etc)
- Expected win probability
- Roll results (raw rolls before crits are applied)
- Crit roll indicator
- Indication of Winner

**Comment by IAmPicard** [comment]
This is a great idea, I hope to get some time soon to work on the gauntlet a bit.

**Comment by IAmPicard** [comment]
I added an initial version of this feature to [release 0.7.1](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.1). Give it a try and let me know how it goes.

The UX still sucks, but there should be an Export button somewhere on that page 😄

**Comment by peachtreerex** [comment]
Thank you so much for following up.  I've had a number of things come up that have prevented me from investigating this.  Will try to take a look within the week, though.

**Comment by peachtreerex** [comment]
This is an awesome step in the right direction

Feedback:

- Skills being tested should be added (CMD / SEC, etc)
- Right now, it only lists one set of "Player Crew stats" and "Opponent Crew Stats".  I would expect that to be two ranges (one for each skill being tested and 0-0 if they don't have that skill
- For ease of data-processing, separating the rolls into individual columns would be a HUGE help
- Also, having separate columns to indicate the crits (rather than it be part of the roll information)
- Ideally, rolls would be displayed without the crits considered.  I know the API returns the total number here, but if you could output the raw roll (so Crit Result / 2) and have separate columns to indicate Crit/No Crit on each roll
- The Min/Max ranges under Player/Opponent Crew Stats would be separate columns as well.
- I don't know if there are privacy implications, here, but I don't see "opponent name" as important information.

**Comment by peachtreerex** [comment]
One more thing that would be nice:

The length of streak prior to this match

**Comment by IAmPicard** [comment]
I've added most of these to [release 0.7.4](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.4) ; please give that a try.

**Comment by peachtreerex** [comment]
I'm pretty sure you hit every single one of my requests.  Awesome.

The only small change I'd like, if possible, is that right now it's showing the streak status AFTER the current match.  Could you update this so it showed the streak status BEFORE the current match?

Basically, there's some amount of controversy that some people claim that you are more likely to lose a match when you are about to get the non merit/credit reward (i.e., 3rd/6th/9th/etc match of a streak).  With what you have now, on a loss, I would have to look back to the previous row to see what the streak was after the last matchup because it lists the consecutive wins as 0.

**Comment by IAmPicard** [comment]
Can you try [release 0.7.5](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.5) ?

For the critical roll, I'l stick with displaying the actual roll number, to remain consistent with the game. The crit boolean is there as well, so we can add a formula to divide if needed in the data analysis.

**Comment by peachtreerex** [comment]
Just tried 0.7.6 and it looks great.  Thank you!

**Comment by IAmPicard** [comment]
Cool, let us know what results you get from the data.
