### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Runisco** [IAmPicard/StarTrekTimelinesSpreadsheet#37]
**Is your feature request related to a problem? Please describe.**
It's always annoying to manually cross out each crew in the voyage suggestion box, of the crew related to the ongoing event

**Describe the solution you'd like**
The easiest and best solution is a tickbox. "Tick here, if you don't want the event crew counted/suggested"

**Additional context**
Tool version: **0.6.9**
Operating system: **win32 x64 (6.1.7601)**

**Comment by IAmPicard** [comment]
Hear you, will look into it.

FWIW, the "crew picker" is based on a textbox, so you can click to set the cursor at the end of the list and just use backspace to clear out the selection.

**Comment by IAmPicard** [comment]
This is fixed with [release 0.7.4](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.4) ; please give that a try.
