### ISSUE TITLE
A query rather than a bug report 

### ISSUE THREAD

**Issue by littlestoatie** [IAmPicard/StarTrekTimelinesSpreadsheet#38]
**Describe the bug**
I notice that when the gauntlet section gives optimal crew selections - it does not include any crew with the command trait unless command is the featured trait. Is there a reason for this?
**To Reproduce**
1. Go to '...'  Gauntlet,  when you have not joined the current in play gauntlet

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by IAmPicard** [comment]
The Gauntlet crew selection could definitely use some input from someone who is more statistically-inclined. The algorithm code is [here](https://github.com/IAmPicard/STTApi/blob/3b5f37b0b61b444d2ad317d3fa81932ad26de5f1/lib/GauntletTools.ts#L257).

Currently, it tries to select crew with the highest proficiency, with a 10% bias towards the featured trait, and a (crit / 3) bias for traits, where crit is 5, 25, 45, etc.

My guess is the reason you're not seeing CMD crew in the selection is that your highest-proficiency crew is lacking CMD skills

**Comment by littlestoatie** [comment]
Ah I see! So there isn't any provision to force inclusion of each skill.  (Guess I need to get better cmd crew!!) :)
