### ISSUE TITLE
Voyage calculator includes shuttle crews

### ISSUE THREAD

**Issue by IanSimcock** [IAmPicard/StarTrekTimelinesSpreadsheet#39]
I used the Voyage calculator today (it's the first time it's every worked for me) and the crew it suggested included one of my crew that was on a shuttle mission.

I tried turning the "Include active (on shuttle) crew" checkbox on and off while recalculating without any effect.

I'm running version 0.6.9 under Windows 8.

Thanks for writing this tool by the way. The gauntlet, and now the voyage, calculators are particularly useful.

**Comment by IAmPicard** [comment]
If you're playing on a different client at the same time as the tool is running, you need to refresh before doing any calculations (you can refresh by clicking on your captain name in upper-left, or just restarting the app).

Even better, try closing the game on other clients (phone, Steam, etc.) before starting the tool, that's the only way to ensure accurate results.

If you're still seeing shuttle crew after restarting and closing other clients, that would be a bug we can look into (but I'd be surprised if that happens with the checkbox off).

**Comment by IAmPicard** [comment]
I'll call this closed for now; didn't receive complaints from anyone else and didn't repro myself.
