### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by Biftekic** [IAmPicard/StarTrekTimelinesSpreadsheet#4]
Recommendations screen is blank while my crew is not on voyage. I cant see any recomendations. I need to send them on voyage, restart startrektimelines tool and then recommendations apear.

**Comment by IAmPicard** [comment]
I'll try to find some time to fix this.
In the meantime, most crew recommendations are available in the Missions tab (for each mission you can see which combination of crew gets what chance of completion) and for duplicates you can sort in the Crew grid.

**Comment by Biftekic** [comment]
No problem. No hurry It is working while crew is on voyage. I'm just trying to help you with all bugs and problems. This is great app. Thank you

**Comment by IAmPicard** [comment]
Can you see if the [new release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.5.8) fixes the issue for you?
This was caused by a feature I started working on for voyage crew recommendations, but never got around to finishing it because my real job got in the way 😃

**Comment by Biftekic** [comment]
I tried it yesterday. Bug was still there. Everything normal when you have ongoing voyage. But when you need to start new voyage and look at recommendation screen you see white screen of death :) and need to restart app.

**Comment by gunpoint45** [comment]
I can confirm this, it happens to me too. Exactly like that. Newest version.

**Comment by IAmPicard** [comment]
I wasn't able to repro this; but I added an option in the [latest release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.5.9) to open the debug pane. If someone could give that a try, it'll help me narrow down the issue:

![image](https://user-images.githubusercontent.com/31076775/34068603-c695e708-e1f2-11e7-95d6-def800ae644f.png)

* Click on your captain name
* Click on the gray bug button in the popup that shows up
* Click on the Console tab in the dev tools
* If you see any errors in the list, please copy-paste those

**Comment by SearchAndDestroy** [comment]
I am also having this, Just updated to v0.5.9.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/551613/34071165-93d7e160-e272-11e7-9f10-0f9b23fb40bb.png)

**Comment by IAmPicard** [comment]
Thank you, I found the issue and fixed it in the [new release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.6.0).

**Comment by IAmPicard** [comment]
I consider this fixed. Please reopen if you're still seeing the issue.
