### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jaspotn** [IAmPicard/StarTrekTimelinesSpreadsheet#42]
**Describe the bug**
There appears to be a recommendation bug for the missions 'Adv: A Certain Formality', 'Down Once More'.
I have fully completed this mission and obtained all rewards under all three difficulty levels however the recommendations are showing the completed status as 2/3,0/3,0/3 (screenshots added showing recommendations and completed status of all three levels)

**To Reproduce**
Go to Missions tab
Choose only show missions that are not fully complete
Cadet - Adv: A Certain Formatlity shows (2/45) even though mission is fully complete.

**Expected behavior**
With option to show only missions that are not fully complete, this missions should not display at all as it is complete

**Screenshots**
![elite](https://user-images.githubusercontent.com/39434813/40268347-dcbe96a6-5baa-11e8-9609-0e9474d724ec.PNG)
![epic](https://user-images.githubusercontent.com/39434813/40268348-dcefc9ec-5baa-11e8-908c-b63b0e22e19a.PNG)
![normal](https://user-images.githubusercontent.com/39434813/40268349-dd211150-5baa-11e8-9e9c-c9e456f4fc3b.PNG)
![recommendation](https://user-images.githubusercontent.com/39434813/40268350-dd509240-5baa-11e8-937c-caa7a4fa2e2b.PNG)

**Additional context**
Tool version: **0.6.9**
Operating system: **win32 x64 (10.0.16299)**

**Comment by IAmPicard** [comment]
That is very weird, I'll try digging through the code a bit.

Is this a node that you recently completed? Do you remember if you had these complete before the first time you started the application? The only thing that comes to mind is some sort of caching bug (although I only cache completed quests).

**Comment by jaspotn** [comment]
No I had all cadet missions completed before I started using the application. As a test I went into the mission on normal run-thorough and selected the two nodes that it shows as incomplete and did them again. No change after a period to allow resync.

**Comment by jaspotn** [comment]
Hi,
Just updating this issue to say I've just tried version 0.7.1 of the client and I'm still getting recommendations to finish this cadet mission even though I have completed it in game.

**Comment by IAmPicard** [comment]
This is the same as [this issue](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/issues/31), and the fix will be included in the next release. Thanks!
