### ISSUE TITLE
Feature request - Button on voyage log to recall - maybe colorvoded for extra visibility?

### ISSUE THREAD

**Issue by Runisco** [IAmPicard/StarTrekTimelinesSpreadsheet#45]
It is not a problem, just an expansion. Would it be possible to add a button to the voyage tab under voyage log, that when clicked will recall the voyage?

If possible, maybe make the button colorcoded depending on how much antimatter is left? < 100 = red, 500-100, orange etc. gradient perhaps?

Hopefully this could be possible as it's not an automatic recall, but a user pressed one.

**Additional context**
Tool version: **0.7.1**
Operating system: **win32 x64 (6.1.7601)**

**Comment by IAmPicard** [comment]
Yes, I think this should be possible. But there are some intricacies that need to be designed first.

This implies that the voyage log will update itself for example, which is currently not the case (you need to leave and return to the tab to get an updated view).

**Comment by Gryphonsdream** [comment]
perhaps an update refresh timer for the log, may be the siplest way.
refresh xx seconds 
where xx is adjustable maybe to alow for some flexibility and not lock up low cpu PCs

**Comment by ThePooBurner** [comment]
I have found that the time remaining on a voyage (once no longer passing) is (antimatter/30)*1.35 = minutes remaining to within 1 minute.  Adding a refresh timer that refreshes the voyage information automatically at a calculated 5 minutes (or user defined time) remaining would be helpful in getting people pretty close to when they want to recall. And then perhaps once the 5 minute refresh happens do 30 second refreshes for those taking it to the last possible second, like i do.
