### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by stephenflore** [IAmPicard/StarTrekTimelinesSpreadsheet#48]
Unable to login from one of two accounts.

One account logs in with no issues.

The other account gets an error message that the database is invalid.

There are multiple differences between the accounts, but the account that I am unable to log on, is also the account that I have an active Captain Rachel Garrett which is a new character in the game.

**Comment by IAmPicard** [comment]
It looks like Garret was added back into the system, so this should be resolved.
