### ISSUE TITLE
Wrong item graphic

### ISSUE THREAD

**Issue by ChewableCPP** [IAmPicard/StarTrekTimelinesSpreadsheet#56]
![image](https://user-images.githubusercontent.com/34800071/40879319-ec3a4794-6652-11e8-8589-1089fcff72b4.png)

No idea if it was always that way or if any other items are affected.

**Comment by IAmPicard** [comment]
I carefully scanned through all my items and I'm not seeing examples of mismatched icons.

I'm wondering if there's something weird in particular about "Will Scarlet" Uniform. If you look for it in the official game, does it look correct?

**Comment by IAmPicard** [comment]
I'm definitely seeing the same thing in the image cache: "c:\Users\.\AppData\Roaming\Star Trek Timelines Crew Management\imagecache\items_equipment_worf_will_scarlet_uniform.png" is this sword, which is just a bigger version of items_equipment_worf_longsword.png

But again, appears limited to this one particular item, so I'd be willing to bet the same thing would show up in the facebook client for this item (at least for the particular version of the bundle that was used when the images were cached).

**Comment by ChewableCPP** [comment]
Unfortunately I have a Steam originated account, so there is no way for me to log into it on FB to check. But it looks fine in the Steam client:

![image](https://user-images.githubusercontent.com/34800071/40879732-28bcfd1e-6659-11e8-976a-f68850bba304.png)

Same on Android.

**Comment by IAmPicard** [comment]
I'm going to chuck this out as random noise and close it for now; will keep an eye out on reports for wrong graphics in the future.
