### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Brian-Ballard** [IAmPicard/StarTrekTimelinesSpreadsheet#59]
**Describe the bug**
Got error message at at startup at calculating mission success stats step:
An error occured while loading data!
Try restarting the application; if the error persists, please log a bug. Details: {}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (6.3.9600)**

Error details: {}

**Comment by IAmPicard** [comment]
This is related to DB requiring all clients to be on version 5.1.0; I just [released 0.7.3](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.3) to fix this.
