### ISSUE TITLE
Bug report - An Error occured while loading data!

### ISSUE THREAD

**Issue by eljay69** [IAmPicard/StarTrekTimelinesSpreadsheet#60]
**Describe the bug**
"An error occurred while loading data!" error message displays when the program is started.  Under the "wait wheel" it says "Calculating mission success stats for crew ...".

**To Reproduce**
Steps to reproduce the behavior:  Just fire up the program.

**Expected behavior**
A clear and concise description of what you expected to happen.  I expected the program to start up as usual.

**Screenshots**
![180606 sttcm v0 7 2 error at startup](https://user-images.githubusercontent.com/39999251/41049480-0253dfb6-697f-11e8-8a8b-75f40869e2dd.png)

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (10.0.16299)**

Error details: {}

**Comment by IAmPicard** [comment]
This is related to DB requiring all clients to be on version 5.1.0; I just [released 0.7.3](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.3) to fix this.
