### ISSUE TITLE
Bug report - an error occured while loading data

### ISSUE THREAD

**Issue by Sesamnos** [IAmPicard/StarTrekTimelinesSpreadsheet#61]
**Describe the bug**

The application has stopped working, It will no longer connect to the game server. I get a popup stating an error occured while loading data. The reason is probably because DB is forcing client version 5.1.0 today.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (10.0.17134)**

Error details: {}

**Comment by IAmPicard** [comment]
This is related to DB requiring all clients to be on version 5.1.0; I just [released 0.7.3](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.3) to fix this.
