### ISSUE TITLE
Bug report  problems loading from windows 10 no stats screens loaded  also signing in this morning there was a problem

### ISSUE THREAD

**Issue by Blade1858** [IAmPicard/StarTrekTimelinesSpreadsheet#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (10.0.17134)**

Error details: {}

**Comment by IAmPicard** [comment]
This is related to DB requiring all clients to be on version 5.1.0; I just [released 0.7.3](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.3) to fix this.
