### ISSUE TITLE
Voyage Event Crew X/O Switch?

### ISSUE THREAD

**Issue by Gryphonsdream** [IAmPicard/StarTrekTimelinesSpreadsheet#65]
**Describe alternatives you've considered**
i love that the Voyage will now cut Event Crew from voyage consideration.
but there are times when i do want those crews considered also, like 20 hours before the event or when i all ready have my primary crews used on shuttles or perhaps out of builds for the time being. plenty of time for a voyage run. 

could you perhaps add an On/Off Check Box to either Include or Exclude the event crews
or perhaps a Deselect/Select All buttons
as some of the lists for events can be rather extensive to X out

**Comment by IAmPicard** [comment]
The UI is not very intuitive, but that list of crew is actually an editable text box. Just click to place the cursor at the end, and hold down backspace to get rid of everyone.

You can also manually add crew in there (it's autocomplete) that for some reason you don't want to go voyage.

I agree adding a "clear" button would save a couple of steps (and help with the UI confusion maybe).

**Comment by IAmPicard** [comment]
This is fixed with [release 0.7.4](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.4) ; please give that a try.
