### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Joker41NAM** [IAmPicard/StarTrekTimelinesSpreadsheet#66]
**Describe the bug**
Got "An error occurred while loading data" message

**To Reproduce**
Launched the program

**Expected behavior**
Load data from STT

**Screenshots**
![image](https://user-images.githubusercontent.com/39820552/41076978-d7f4b460-69d9-11e8-90da-5211d7617cdd.png)

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (10.0.17134)**

Error details: {}

**Comment by sbrandsvb** [comment]
Same issue here, both for me and my husband.

**Comment by IAmPicard** [comment]
This is related to DB requiring all clients to be on version 5.1.0; I [released 0.7.3](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.3) to fix this.
