### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Runisco** [IAmPicard/StarTrekTimelinesSpreadsheet#68]
**Describe the bug**
Begins to cache everything, then it just stops. An error occured while loading data!
Try restarting the application; if the error persists, please log a bug. Details: {}

Restarting does nothing

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (6.1.7601)**

Error details: {}

**Comment by IAmPicard** [comment]
This is related to DB requiring all clients to be on version 5.1.0; I [released 0.7.3](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.3) to fix this.
