### ISSUE TITLE
Failure to Load

### ISSUE THREAD

**Issue by ShashPNW** [IAmPicard/StarTrekTimelinesSpreadsheet#69]
**Describe the bug**
Failure to load

**To Reproduce**
Steps to reproduce the behavior: Start the application

**Expected behavior**
I expected the program to load

**Screenshots**
![screenshot 2](https://user-images.githubusercontent.com/40044376/41132090-c64dad8a-6a73-11e8-85b8-338bf770ab65.png)

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (10.0.17682)**

Error details: {}

**Comment by IAmPicard** [comment]
This is related to DB requiring all clients to be on version 5.1.0; I [released version 0.7.3 of the tool](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.3) to fix it.

**Comment by ShashPNW** [comment]
After doing a little digging, I found that.  I was coming back to close the
thread, but you were obviously online, and beat me to it.  Updated, and
working fine again, thanks.
