### ISSUE TITLE
Signing in for the STT (Add on) Crew Spreadsheet

### ISSUE THREAD

**Issue by Sashasonic** [IAmPicard/StarTrekTimelinesSpreadsheet#7]
Hi,

Didn't know how to delete this question - but found the [correct place for it](https://github.com/IAmPicard/STTGoogleSheetsAddon/issues/2) 

Thanks again, your STT resources are excellent.
Sasha.

**Comment by IAmPicard** [comment]
This was moved to the add-on repo.
