### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jaspotn** [IAmPicard/StarTrekTimelinesSpreadsheet#70]
**Describe the bug**
Upon launching the application I get an error stating 'An error occured while loading the data!' Restarting the application a few times just gives the same error

**To Reproduce**
Try to open the application

**Expected behavior**
The program should load

**Screenshots**
![image](https://user-images.githubusercontent.com/39434813/41150023-301bbc38-6b4c-11e8-96d6-da9a9afd75b3.png)

**Additional context**
Tool version: **0.7.2**
Operating system: **win32 x64 (10.0.17134)**

Error details: {}

**Comment by Sashasonic** [comment]
Usually means you need the [updated version]https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releasesl) which is 0.7.3.

**Comment by jaspotn** [comment]
Done and it appears to work! Got an update notification for 0.7.1 to 0.7.2 so wasn't aware 0.7.3 was released. Will close issue now.
