### ISSUE TITLE
Fleet Chat history pulls older chats instead of new

### ISSUE THREAD

**Issue by to11mtm** [IAmPicard/StarTrekTimelinesSpreadsheet#72]
**Describe the bug**
When looking at Fleet chat history, older messages are shown instead of newer.

**To Reproduce**
Be in a chatty fleet where more than 30 messages are done in a short period of time.

**Expected behavior**
Newest 30 chats to be displayed

**Screenshots**
N/A

**Additional context**
Tool version: **0.7.3**
Operating system: **win32 x64 (10.0.17134)**

I made a pull request after troubleshooting the problem in the debugger. (https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/pull/71)

**Comment by IAmPicard** [comment]
Thank you, I merged your PR.

If you're interested in improving the chat support (I personally always hated typing on the small phone keyboard and as a result don't communicate much with my fleet), please keep them coming.

**Comment by to11mtm** [comment]
There are a couple things I'd like to try out, but I'm having problems with the build instructions. Can you list what windows SDKs and/or versions of visual studio you have installed? one of the node packages is looking for a specific version of VCBuild.exe but it's not being forthcoming as to which.

**Comment by IAmPicard** [comment]
I'm developing on Windows 10, over a couple of different versions. I'm currently running the latest available public update. If you don't want to install VisualStudio and all that, you can just install '[windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)' (`npm install --global --production windows-build-tools`).

For Visual Studio, I have 2017 installed; there is a free version called [community edition](https://www.visualstudio.com/vs/community/).

I have also built successfully on macOS and Linux (just install a recent version of GCC and you should be good).

**Comment by to11mtm** [comment]
Ahh. Well I had VS 2017 Community installed all the way beforehand and was getting the error, so I was totally lost.

The NPM command you gave did the job for me. I didn't do the `--global --production` before (I'm a .NET guy by trade, never dealt with NPM) and that was the problem.

So... I'll see what I can do. Thank you!
