### ISSUE TITLE
Feature Request - Add control toclear voyage excluded crew list

### ISSUE THREAD

**Issue by ChewableCPP** [IAmPicard/StarTrekTimelinesSpreadsheet#73]
For faction events, it would be nice to have a simple control to clear the excluded crew list (rather than backspacing them all), since typically the crew that need to be excluded are already on a shuttle at the time.

**Comment by IAmPicard** [comment]
This is fixed with [release 0.7.4](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.4) ; please give that a try.
