### ISSUE TITLE
Bug report - Voyages falling far short of estimates

### ISSUE THREAD

**Issue by j59723** [IAmPicard/StarTrekTimelinesSpreadsheet#76]
My voyages are failing about 30+ minutes before the estimate for the last couple of weeks

Up until one of the recent updates (I believe around the update to version 5), voyage estimations were very accurate. Lately they've been overestimating my voyages by at least 30 min.

Tool version: 0.7.3
Operating system: win32 x64 (10.0.17134.81)

If there is a way to just send data for better analysis, I'd be happy to do so if it means less work for you. Thanks for all that you do!

**Comment by ChewableCPP** [comment]
I haven't noticed or heard of anything changing. But definitely keep an eye on it. You could be right.

A 30 minute deviation is possible, though, just from RNG (probably even 60 minutes is possible in some cases). It depends on what kind of proficiency rolls you're using and the distribution of the skills.

Check out my javascript tool here - it more accurately simulates the range of outcomes and visualizes them: https://codepen.io/somnivore/full/Nabyzw/

That tool doesn't know your actual proficiency rolls, though, so you can play with the % Proficiency setting. I think the default of 20% is probably higher than what most voyage crews actually have, but I'm not sure - it was a guesstimate, but it doesn't affect the average estimate much, mostly the range of outcomes.

**Comment by ChewableCPP** [comment]
Thinking back, my last few voyages actually beat out the estimate.

**Comment by j59723** [comment]
I do seem to remember some hubbub on the forums about changes in voyages around the time this began, but can't be sure. I'll check my estimates with ChewableCPP's tool for my next few voyages and let you know what I find, could just be bad luck with RNG.

Thanks guys!

**Comment by ChewableCPP** [comment]
My current voyage is set to substantially exceed the estimate.

**Comment by Gryphonsdream** [comment]
i am a bit undecided on this one, i have had some fall short, i have had some run long, just this past night i had listed to only hit 7.6 and i went for over 8.25 hours so we have to expect some flex given DB and their RNG, especialy as theykeep messing with their RNG

**Comment by ChewableCPP** [comment]
Yeah, pretty sure it's fine.

Unless your result is totally out of range or consistently skewed on one end of the range, then it's pretty impractical to deduce anything just from your own results. You need a much bigger sample size.

What I need to do is incorporate the full range/probability calculation/display, so people have a better idea of what to expect. The single number given now is just an average.

**Comment by j59723** [comment]
Finished up some voyages, but lost the data for a couple so I only have 6 to work with, but it looks as though everything is working fine:

est:       duration:
8.15	     7h54m
7.72	     7h49m
8.16	     8h01m
7.76	     7h40m
8.12	     8h25m
8.15	     7h58m

The results seem well within the margins of what is to be expected from RNG, it seems I just had an overly long streak of bad luck, but all seems to be working well on your end. Thanks for the tool and keep up the good work y'all!

**Comment by IAmPicard** [comment]
I'll close this for now. I've been thinking of a feature to allow users to upload their results and initial estimates to some location (perhaps a google spreadsheet). That way, we can correlate from multiple data sets, identify trends and maybe improve the algorithm.

But I couldn't find an API to upload to a public google spreadsheet without authentication.
