### ISSUE TITLE
Bug report: Stay Logged In doesn't work

### ISSUE THREAD

**Issue by dewittified** [IAmPicard/StarTrekTimelinesSpreadsheet#78]
**Describe the bug**
Whether using Stay Logged In or not, I am automatically logged into my last account. 

**To Reproduce**
Uncheck Stay Logged In, log in. Close app. Open. Am immediately logged in. Log out, close app. Open app, am immediately logged in.

**Expected behavior**
I assume that each time the app opened, it would prompt for a login, if it was not set to stay logged in.

**Screenshots**
n/a

**Additional context**
Tool version: **0.7.3**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
Can you try [release 0.7.5](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.5) ? I believe I fixed this issue.

**Comment by IAmPicard** [comment]
Fixed with 0e7684aa9c3ca3ef4faf94743bd36116ec743428
