### ISSUE TITLE
Arena Data List With the Crew List Maybe???

### ISSUE THREAD

**Issue by Gryphonsdream** [IAmPicard/StarTrekTimelinesSpreadsheet#79]
I know this request is more fluff than any things else, and not a priority, but
could it pe added to pull the areana crew data when pulling the clrew tab list or even on second page.
*Ship basic Stat
Boosts | Value | Handicap | Value | 
*Special Boosts
Shield Regen | Repair Shield | Repair Hull | Att Speed | Damage % | Crit Rating | Crit Bonus
Ship Trigger | Charging Time | # Uses
*Timings
Initialize | Duration | Cooldown
*Equip,emt Bonus
Accuracy | Evasion | Crit Rating | Crit Bonus | Skill Trigger1 | Skill Trigger2 | Skill Trigger3

Example
crew              |  Boost  | HCap | Initialize | Duration | Cooldown | # uses |  
Ensign Pazlar | Att +2 | —  — |     —0     |      12      |       10       |    —    |

| Acc | Eva | CritR | CritB | skl1 | skl2   | skl3
| 130 | 475 |  5    |  190   | SCI  | COM | —

| SpclBns | shd-GenRep hull-rep  | bns spd/dmg/crtR/crtB | Triger |    Charging time     |
| Att +3   |    —    |    —    |    —   |   —   |  —   |  —   |    —  | Board |  6s, 4Att | 14s, 6Att | 

Image Example from my gathered Data Base
![capture](https://user-images.githubusercontent.com/37913328/41510851-bba130b4-7239-11e8-8453-5af6efeb5993.PNG)

**Comment by IAmPicard** [comment]
I think adding it to the main table would make it too unreadable (unless I introduce a configuration system for users to choose the columns they want displayed), but I could add it to the Excel / CSV export; would that work?

How do you use that data to make decisions? Do you use it to somehow match crew with ships for arena / ship battles? I'd be curious if you can walk through your process a bit, maybe we can help other players by translating that into an automated algorithm.

**Comment by Gryphonsdream** [comment]
i use it to find best crew for a given ship and its abilities for arena yes, 
beginning with what ship slots are available (COM, DIP, ENG, SEC, SCI, MED)
then by ship abilities (Blank, Boarding, Cloak, Position) so i narrow down low value crew quickly
sorted on highest Values to Att, Acc, Eva, some over shadowed or compounded by bonus ability.
i also consider bonus equip stats total value, timings, and uses,

in my case i like fast acting damage boost % with short timing and higher eqip stats in Acc and Eva. 
better to have a longer initialize and a short cool down vs long cool down where it can be done.

my typical crew on Adm Arena 
Bounty with 
Tkuvma (375%), Susna Sarek (400%), Proton Paris (Eq Numbers and evade), Mirror Phlox (200%)
order of activation, 
ship Att boost, then Cloak to evade target high damage, then
paris for evade, phlox for acc and 200% base, Tkuvma for 18 att and 375%, followed by Sarek for his 400%
if i dont have an insta kill i continue with ship ACC and ATT, till Cloak comes active again
there are only a few configurations i have trouble with, and those are mostly because i miss my timing.

there is an algorithm to it but i do a lot of it in my head
curse of paying tactical games i guess,

**Comment by Gryphonsdream** [comment]
having the data available for export would be grand.

**Comment by IAmPicard** [comment]
I added most of these with [release 0.7.4](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.4) ; please give that a try.

**Comment by Gryphonsdream** [comment]
absolutly loving the excel output. ty ty

**Comment by IAmPicard** [comment]
Thanks
