### ISSUE TITLE
Recommendations not displaying properly

### ISSUE THREAD

**Issue by orangefoodie** [IAmPicard/StarTrekTimelinesSpreadsheet#8]
![image](https://user-images.githubusercontent.com/35016955/34472619-d4a5c554-ef1a-11e7-99a4-a070a8e4883f.png)

As the image shows, the recommendations aren't displaying properly as of like 2 days ago? Please let me know if there's anything I can do to help!

I'm running Win7 x64 if that helps?

**Comment by IAmPicard** [comment]
I realize that the UI is not very friendly (I'm usually a back-end developer and just hate HTML 😄), but those down-arrow buttons (to the left of the section titles) are supposed to be expanders. If you click on one, do you see a bunch of stuff coming in?

**Comment by orangefoodie** [comment]
I totally don't blame you for hating HTML! 😆 
As you can see, the other expandos work, just not the voyage recommendations! They seem to have borked when the last event started?

Thank you for your effort making this thing, it's amazing!

![image](https://user-images.githubusercontent.com/35016955/34547453-1a26335c-f0b0-11e7-95f4-7bf7794355e7.png)

**Comment by IAmPicard** [comment]
Oh, I see. The Voyage recommendations are not implemented yet; that's a feature I started but never got around to finishing. I hope to find some time this month to work on it.

**Comment by orangefoodie** [comment]
Well, iunno what happened but it seems to be working again?

![image](https://user-images.githubusercontent.com/35016955/34624216-53766456-f209-11e7-8f24-a41d645f2dc8.png)

**Comment by IAmPicard** [comment]
That was actually part of a feature I never finished. FWIW, I polished it up a bit now, but I still wouldn't call it ready for use. The algorithm is suboptimal and needs some improvements:

![image](https://user-images.githubusercontent.com/31076775/35470629-beaf2e34-0301-11e8-82a6-c69a134eff4f.png)

**Comment by IAmPicard** [comment]
FWIW, this is included in the [latest release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.6.3), give it a go.

**Comment by orangefoodie** [comment]
Thank you so so much! I gave it a whirl and a few notes:

1) The version number on the binary still says 0.6.3! Just giving you a hard time :)
2) For whatever reason, the score isn't displaying for me, and nor is the correct order of appearance - ie yours has First Officer, Helm Officer, Comms Officer etc in that order but mine is all jumbled.
3) Also would it be possible to have an option in settings to display an average stat value of (base skill)+(average of random component) in the crew list?

Thanks so much again for your amazing work!

![image](https://user-images.githubusercontent.com/35016955/36626396-e53f5074-18e6-11e8-8951-9ce1a6d8e707.png)

**Comment by ChewableCPP** [comment]
It's not just you. The UI is still crude :p

We're focusing on the algorithm itself at the moment but hopefully the UI will get beefed up eventually.

You'll notice the current order isn't "jumbled", it's alphabetized by the slot name. Still usable, but not as nice, I agree.

**Comment by IAmPicard** [comment]
Lots of improvements with the latest release to the voyage interfaces. Still a ways to go, but calling this closed for now.
