### ISSUE TITLE
Feature request - Ability to dismiss crew?

### ISSUE THREAD

**Issue by QHsapko** [IAmPicard/StarTrekTimelinesSpreadsheet#80]
Ability to dismiss crew especially multi select dismiss. Recently used your tool to play the gauntlet and noticed how quick the battles are since there are no animations. I think this would be helpful with dismissing crew especially from overflow when doing a lot of pulls and ending up with dozens or more crew that need to be dismissed. It can take hours to dismiss all crew for whales, not me :) . I think it's important to help them make spending as painless as possible. Thanks.

**Comment by QHEricNelson** [comment]
That would be awesome!  Great idea -- I'd definitely go from a "probably won't ever use it" to an enthusiastic "gotta use it after going on a Dilithium binge" user.  :-)

**Comment by ThePooBurner** [comment]
I would also love to see this added.

**Comment by IAmPicard** [comment]
This is fixed in [release 0.7.7](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.7).
