### ISSUE TITLE
Crew ranking

### ISSUE THREAD

**Issue by Cagey-1** [IAmPicard/StarTrekTimelinesSpreadsheet#83]
Could you add personal ranking for each character for voyages and gauntlet? Percentile based?

**Comment by IAmPicard** [comment]
What do you mean? You have a preference for particular characters and want the recommendation algorithms to favor those characters even if others in your roster provide better results?

**Comment by Cagey-1** [comment]
I was thinking of score based for each type.  Then assigned a percentile based on your crew.  So you could see whom is in say your top 20%.  It would give users better understanding of which to keep out or freeze. I've used your sheet add-on to do it for me but was thinking others would find it useful.

**Comment by IAmPicard** [comment]
I see. For voyages, @ChewableCPP added a nice feature to get this ranking. You can find it here:
![image](https://user-images.githubusercontent.com/31076775/42068675-5569e6ac-7b02-11e8-95fd-67a56ddb8a53.png)

I had to turn off frozen crew support at some point (to fix a bug), and never went back to re-add it 😞. It'd definitely help with the usefulness of that feature.

For gauntlet, I'll have to think a bit about how to optimize / sort the list.

**Comment by Cagey-1** [comment]
I have attempted to use the Export with Voyage ranking. It seems to be broken. I click and it does nothing or the app freezes.

**Comment by Cagey-1** [comment]
Okay. It works and it takes longer than what I was expecting. (And I would click it again.) Guess that's why I though it was broken. Lol. Still looking at the numbers. Thanks
