### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nikdollas** [IAmPicard/StarTrekTimelinesSpreadsheet#84]
Hi ! Good job !

However an issue. In gauntlet section chance needs to get reworked. I loose all conflicts that show bellow 75%. That doesn't seem to precise in my opinion.

**Comment by IAmPicard** [comment]
Please use the Export log option and upload the csv file here, we can take a look at the data.

FWIW, I've seen failures with 99% chance... at the end of the day that's still 1 in 100 chance of failure and RNG is RNG...

**Comment by IAmPicard** [comment]
Closing this for now. See analysis done by Peachtree [on the forums](https://forum.disruptorbeam.com/stt/discussion/11125/2500-rounds-of-gauntlet-data) which indicate the percentage is pretty much spot-on (within error margin).
