### ISSUE TITLE
"Needed Equipment" improvements

### ISSUE THREAD

**Issue by fyreflow** [IAmPicard/StarTrekTimelinesSpreadsheet#85]
This new addition is great - I definitely see myself using it often.

I just need clarification on a few points: 
- Are these the total quantities of each item needed, irrespective of what is in your inventory, or does it display the number of items you _still_ need over and above what you already have?
- Does it ignore crew in "trashcan countdown", or include them?

And a few improvements that would make it even better:
- Having it either alphabetized or searchable, as it is quite an extensive list for anyone who isn't in the endgame.
- Being able to export it to .csv (just item name, rarity and quantity would be fine).
- If it only displays the total needed, then linking to your current inventory to also show you the balance that still needs to be farmed, would be a big plus.  Even better if the list was sortable by these quantities (but if it's exportable, that would be a workaround for that).

**Comment by IAmPicard** [comment]
Yes, it doesn't currently subtract the number of items you already have in the inventory; I'll add that number in as well.
It doesn't ignore buyback crew, but it probably should; I'll look into fixing this as well.

Thanks for the suggestions. This feature is still a very early preview, and needs lots of work.

My goal was to get a list of the most needed items (in particular the hard to get ones such as faction-only), and later integrate that with a "replicator helper" feature that will tell you know what items you need and cannot easily farm, as well as what items have no value and can be burned (like ship schematics for maxed-out ships, or high level equipment for crew you already FE-d and stuff like that).
Shuttles are also something I want to get to at some point (a crew recommendation for shuttles, as well as recommendation for which faction to go after based partially on the needed equipment found here).

**Comment by fyreflow** [comment]
This is fantastic! It is my number one favourite feature of the application now.

What does the percentage values represent? Chance of dropping per single run?  What is the source of these?

**Comment by IAmPicard** [comment]
I believe those are the actual drop chances, in the API they’re called energy quotient; in the game UI they’re used to sort the item sources, which would support that as well.

**Comment by fyreflow** [comment]
That's very interesting - I had no idea that was able to be extracted.

Except that the observed "yields" in die wiki droptests do not conform to the same ranking order that the game displays for missions, so there is a disconnect somewhere between these and the actual results, it seems.  Or perhaps there is a way to reconcile these two sets of data - I'll pay closer attention to that from now on.

**Comment by jstuart99705** [comment]
Not sure if it's a bug or maybe I'm reading it wrong but not sure if the program is calculating correctly. I am working on First Officer Saru's 5 Star Uniform. For the uniform, I need 2 4 star uniforms and each one requires 1, 3 Star Gold Pressed Latinum. I currently have one but the app is saying Gold-Pressed Latinum (for the 3 star) (need 1, have 1) .

Same with Fur's. For his uniform alone I need 2*4 Star Uniform that would need 8 furs but the program is saying Furs (need 6, have 0)

**Comment by fyreflow** [comment]
@jstuart99705 My first thought is that the application's data might be out of date for the current state of your crew - it doesn't refresh itself unless prompted.  Did you restart the application/refresh data after adding the latest levels to First Officer Saru? Also, are both 4* uniforms not built yet?

**Comment by jstuart99705** [comment]
I did, I installed the update checked the required items, closed out and then came home and opened the app again. He has been at level 100 with all 4 equipment slots vacant for a day or so and neither of the 4* are built yet.

**Comment by IAmPicard** [comment]
I think I found the problem. A recipe can include more than one of the same kind of item. And this compounds as you expand a recipe. If item A needs 2 Bs, and item B needs 2 Cs, then you need 4 Cs to make an A, whereas with my current logic you'd only see 1 C.

I'm attempting to fix it now.

**Comment by jstuart99705** [comment]
That makes sense. When I figure out what I need I start at the top and multiply down until I know how many I need. 

One other suggestion for improvement if it's possible and not a lot of work is on the reccomendation page, list what mission number, the name is. IE Rabid Fans (CT-M2). If this would cause a lot of work no worries, I search via my app or on the Missons Tab.

**Comment by ThePooBurner** [comment]
Listing the mission number would be very helpful.
As for the energy quotient, that is the DB generated number that references chroniton efficiency, not drop chance. So it has to do with how many chronitons it will cost you per item to get them.  However, in practice they don't always have it sorted correctly.  There are some missions that are dramatically better in terms of drop rate than the ones listed above it in the mission selection UI.

**Comment by IAmPicard** [comment]
Lots of improvements to the needed equipment section are already added. Calling this done.
