### ISSUE TITLE
Gauntlet, % rate in question

### ISSUE THREAD

**Issue by Gryphonsdream** [IAmPicard/StarTrekTimelinesSpreadsheet#88]
**Describe the bug**
i have been noticing a higher than normal of +90% failures.
am i just geting slammed by RNG or is some thing off
i have actualy had better luck with the 50% matches

**To Reproduce**
gauntlet, run 90% or better match and loose 2/5 or more
i have gotten a couple 100% and 99% failures.

**Expected behavior**
i figure 1 or 2 in 10 loss, but not this many,

my gauntlets have been prety short as of late.

**Comment by IAmPicard** [comment]
Nothing changed in how I calculate chance percentage. Can you export the gauntlet log and upload it here (it'll be a CSV file). FWIW, I've seen failures with 99% ; 99% still means 1 in every 100 such rounds will end in a lose.

**Comment by Gryphonsdream** [comment]
well i am guessing i just had a realy realy bad RNG run as it did clear up, only had 1 95% loss recently.
i did note a while back that some oponent crew that had over 1000 on a single skill wernt displaying right in the game and might have been a contributing issue in the manager tool also. may have thrown off the calculations, IDK, 
in cases where an opponent had over 1000 on a skill the data was dropping the 1000 in the displayed chalenges. IE 1010 to 1400 would display 10 to 400 in the game view. and wouldnt show the right numbers till after choosing my crew and sending it.
not sure if the manager app would be effected by the same thing if DB output is wrong then bumps after.
i tend to run both the game and the app open at the same time and was using the game for refresh of options. but recently hanvet been doing so. might have explained my losses if this is still happening.

**Comment by IAmPicard** [comment]
Closing this for now. See analysis done by Peachtree [on the forums](https://forum.disruptorbeam.com/stt/discussion/11125/2500-rounds-of-gauntlet-data) which indicate the percentage is pretty much spot-on (within error margin).
