### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Brutail** [IAmPicard/StarTrekTimelinesSpreadsheet#89]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

Error details: Error: Network error; status 500; reply NoMethodError (undefined method `to_hash' for nil:NilClass):
app/models/event/faction_winner.rb:42:in `to_hash'
app/models/faction/desc.rb:74:in `block in full_description_for_reputation'
app/models/faction/desc.rb:74:in `map'
app/models/faction/desc.rb:74:in `full_description_for_reputation'
app/models/faction/desc.rb:162:in `block in faction_descriptions_for_character'
app/models/faction/desc.rb:160:in `each'
app/models/faction/desc.rb:160:in `faction_descriptions_for_character'
app/models/character.rb:225:in `full_description'
app/models/player.rb:91:in `to_hash'
app/controllers/player_controller.rb:240:in `block in index'
app/models/change_tracker.rb:10:in `track'
app/controllers/player_controller.rb:239:in `index'
app/controllers/application_controller.rb:45:in `record_client_api'
app/controllers/application_controller.rb:30:in `purge_thread_around'.

**Comment by IAmPicard** [comment]
Do you still repro this? Was it perhaps related to the server outage earlier today?

**Comment by Brutail** [comment]
Its ok now. Server was down

Dňa po, 2. júl 2018 20:22 IAmPicard <notifications@github.com> napísal(a):
