### ISSUE TITLE
Recommendation: Add an export function to the Fleet tab?

### ISSUE THREAD

**Issue by FortKnox1337** [IAmPicard/StarTrekTimelinesSpreadsheet#9]
Hey,

Is it possible to add an export function to the fleet tab just like you have on the crew tab? As a fleet we keep a close eye on Participation levels and usually take screenshots just before every reset to see how our members are doing. But with your app it would be great to be able to export that information for an easier copy and paste job.

Luke.

**Comment by IAmPicard** [comment]
I added a quick&dirty solution for this. Check out the [latest release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.6.1).

**Comment by FortKnox1337** [comment]
Wow that was quick. Amazing. Cheers 🥇
