### ISSUE TITLE
Feature Request - Select crew in needed equipment

### ISSUE THREAD

**Issue by CaptainMarvin** [IAmPicard/StarTrekTimelinesSpreadsheet#90]
Hello, 

I really like the needed equipment section, it is very useful for seeing what i need for crew,
I love using this for gauntlet it's very useful and the new features you just added recently are a great improvement.

I would like some clarification on what the needed equipment section is measuring... 
1. is this the equipment that i need to get all of my crew up to level 100 from where they are now?)
2. is it the equipment i need to get all of the open/unlocked equipment slots filled 
3. is is something else

I currently have about 40 crew at level 1 so clarification on what it's merasuring would be great 

**Feature Request -** wise I suppose i would like to select the crew member(s) that i would like to upgrade. 

I have 5-6 at level 70 so i would like to move them all to level 80+ so select those 5-6 (or however many) and have it give me the needed items for those people only. i also think that we could have some kind of priority to it, i have 1500 alcohol and need 37 i'm not sure that should be on the list as it's not an item i need (but i can see the argument for including it) i just would like to be able to filter it out in the spreadsheet easier (perhaps an additional column "Needed" (yes/no)) based on the results of needed vs have columns.

thanks again for the program,

**Comment by IAmPicard** [comment]
There are a couple of checkboxes in the [new release](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/releases/tag/v0.7.7), one of which limits the display / calculations only to favorite crew (the crew you favorited in the game). I think this will address your need.

Regarding clarification, this is 2 (equipment you need to fill all currently open slots).

**Comment by CaptainMarvin** [comment]
Thanks it works great
