### ISSUE TITLE
Feature Request - Needed Equipment, Cadet Missions

### ISSUE THREAD

**Issue by Joker41NAM** [IAmPicard/StarTrekTimelinesSpreadsheet#92]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the Recommendations\Needed Equipment section, could you add a section for Cadet Missions, like you have for Faction Transmission (as a separate section, not a tack-on to the Missions section)

**Describe alternatives you've considered**
Including them in the Missions section

**Additional context**
Like shuttles can be used to get some components, cadet missions can also be used this way, especially for hard-to-acquire items like 2* IDICs, 2* Encoded Transmissions, 0* Medical Textbooks, 0* Holoprograms, and 0* Science Experiments.

**Comment by IAmPicard** [comment]
This is doable, but it'll take some work.

Reference for whenever someone implements this:
In the item recipe tree, we have item sources which includes quests, ship battles and faction / shuttles, but it doesn't include the cadet missions.
Those would need to be obtained by going backwards from the cadet mission quests description  (.mastery_levels[0, 1, 2].rewards.filter(r => r.type === 0).potential_rewards)

**Comment by lordasti** [comment]
Added PR #133
