### ISSUE TITLE
Feature Request: Voyage Remaining Estimator

### ISSUE THREAD

**Issue by to11mtm** [IAmPicard/StarTrekTimelinesSpreadsheet#93]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could see an estimate of Remaining voyage time, and perhaps some sort of special icon/warning if AM is very likely to run out before the next dilemma.

**Describe the solution you'd like**
Using the method from the @ChewableCPP online calculation tool (or some sort of mildly tweaked version) to calculate remaining time and/or a percentage of likelyhood the next dilemma will be hit.

**Describe alternatives you've considered**
I mean, Manually entering my numbers on the codepen JS page...

**Additional context**
N/A

**Comment by IAmPicard** [comment]
Yes, this was asked for before, but it goes hand-in-hand with an auto-refreshing voyage log of sorts, it wouldn't be much value displaying an outdated snapshot of the info in the page (and manually require users to refresh for updates).

**Comment by ChewableCPP** [comment]
Even a manual refresh would be useful though. I do want to add it at some point.

Note that the codepen method does take considerable time to execute so auto-refreshing that would be quite costly, though it could probably be sped up by native code.

**Comment by to11mtm** [comment]
Putting some notes here; I intend to play around with this a little bit once I have some free time (RL getting in the way at the moment.)

But from a manual refresh standpoint, we could track the last time we checked the calculation, this would let us provide some nice 'hinting' in the UI that maybe after, say, 5 minutes the color changes or a warning icon is added that the refresh button should be clicked.

> Note that the codepen method does take considerable time to execute so auto-refreshing that would be quite costly, though it could probably be sped up by native code.

Interesting. I'll admit I only run the codepen page on my main PC, but it's never seemed slow to me. ;)

**Comment by IAmPicard** [comment]
This feature was implemented and will be available in the next release.
