### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Afrim124** [IAmPicard/StarTrekTimelinesSpreadsheet#94]
**Is your feature request related to a problem? Please describe.**
When doing the Advanced cadet challenges, of "United Federation", I find that the challenge called "Of Two Evils" needs 3-star crew, and the recommendations you make are for 2-star crew.

**Describe the solution you'd like**
I would like that you make recommendations EVEN for crew I don't yet have, so that I know which ones I have to keep an eye open for during the game.

**Describe alternatives you've considered**
???

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.16299)**

Greets,
Afrim Besten

**Comment by Afrim124** [comment]
I found the recommendations useful, when I applied them on Tuesday, and I tried to buy you a coffee, but you need a credit card or a Stripe(?)-account, for which you need to own a business. So I didn't buy you one, since I don't have a credit card and I don't have a business.

Cheers,
Afrim Besten

**Comment by IAmPicard** [comment]
I don't see 2-star crew recommended for "Of Two Evils" part of the Adv. United Federation cadet; There's another mission called "Of Two Evils" in the regular United Federation cadet, maybe those get confused somehow?

About recommendations for crew you don't own; unfortunately, that information isn't available from the API, so I'd need to depend on it from an external source (like the wiki), which in the past has proven to be very unreliable.

**Comment by Afrim124** [comment]
Yes, you're right: They got confused in my head, because I didn't realize
there are two United Federation-challenges. That's why, on sunday, I
couldn't use the recommendations for the tuesday-challenge, because they
were for two-star crew.

I also have a problem with the sunday-challenge, that at the end of the
last mission I need a rare crew member with strong command skills, but I
don´t seem to have one. Fortunately, there is the STT wiki-forums and there
I found the (klingon, veteran, duelist) crew members that will help me
complete the last sunday-challenge.

Thanks for your support!

Kind regards,
Afrim Besten

Op vr 20 jul. 2018 06:46 schreef IAmPicard <notifications@github.com>:

**Comment by IAmPicard** [comment]
The recommendations only take Elite into account and are not too smart (for example, if you need to intentionally fail a node in order to hit a crit threshold, that won'be displayed as an option). I added a note about the mastery level for which it calculates to hopefully make things more clear.
