### ISSUE TITLE
Just a question regarding STT API and Voyage ID

### ISSUE THREAD

**Issue by Runisco** [IAmPicard/StarTrekTimelinesSpreadsheet#95]
As a relative python virgin, I'm trying to see if I can port some of the work over to Python. I am mostly interested, atm, in voyages.

I have gotten the login to work without much of a problem, gotten both tokens and do math to see if it's old. 

However, I am now stuck on voyage.id . Is there any way, API wise, of getting the ID of the active voyage of the logged in user? My first assumption is that you save the voyage id to file in the moment you create a voyage, in which case I'm frelled. And my hope is that you can get the voyage.id through the API somehow.

**Comment by IAmPicard** [comment]
Get the "/player" endpoint, then parse that JSON and extract the current voyage id from this path: data.character.voyage[0].id

FWIW, I strongly recommend taking another look at JavaScript. I never thought I'd be singing the praises of JS (am a hardcore c++ guy myself), but lately I've found it to be very versatile; at work, we've switched a lot of internal tooling over from Perl and Python, and we're writing shipping features with it on desktop, mobile and cloud.

**Comment by Runisco** [comment]
Looking into JS is in the plan, as soon as I feel more stable in python. DOn't really want to switch too often when the information is still relatively new.

May I ask how you discovered/how you discover these endpoints and what information you need to include to properly use it?

**Comment by IAmPicard** [comment]
Sure, I used the Chrome debugging tools (Network tab) with the Facebook version of the game.

**Comment by Runisco** [comment]
Oh that was a fun feeling. I've never done anything like this before, so I decided to try it out with the dabo wheel.

I opened it, and pressed spin. Saw a call to "dabo/spin", so I used your executepostrequest to it, after preparing print commands with [3]['rewards']['loot'][0]['full_name'], started the script and it printed the correct reward, which I then double checked by logging into the game.

A little weird to get an adrenaline rush for coding :P 

Now I need to figure out how to connect my ipad/steam game, where I have all my progress, with facebook, so I can check out the rest.

**Comment by Runisco** [comment]
Another question I hope you don't mind.
I am stumped on one aspect of voyages, because I cannot access voyage dilemmas on facebook, only by accessing my actual game using the login information. So I learn location using facebook, access it only by running the script using my proper account.

So onto the question. STTApi.executePostRequest("voyage/resolve_dilemma", { voyage_status_id: voyageId, dilemma_id: dilemmaId, resolution_index: index });
Voyage id and dilemma id is easy enough. But what does resolution index refer to?

**Comment by IAmPicard** [comment]
You can look at how I used that function from the now-deprecated [voyage monitor application](https://github.com/IAmPicard/STTVoyage).

I hope you're not planning anything nefarious with the voyage API though... I recommend giving DB's [Terms of Service](https://www.disruptorbeam.com/tos/) a read, particularly the section around "macro".

**Comment by Runisco** [comment]
Nothing I am planning is done automatically. Everything requires a manual button push.

**Comment by IAmPicard** [comment]
Closing for now; let me know if I can help with more questions on the API. Also, if you plan on picking up JavaScript, contributions are welcome.
