### ISSUE TITLE
Feature Request - Needed Equipment, Cost/Unit and Runs/Unit

### ISSUE THREAD

**Issue by Tajah** [IAmPicard/StarTrekTimelinesSpreadsheet#96]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The addition of the lowest cost/unit and runs/unit for each equipment in the needed equipment feature, like the STT wiki does. This would help alot when it comes to sorting items by cost and output in the csv export.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Tajah** [comment]
If you search any item, say Casing, then scroll down there are sortable tables for each rarity. Each table has all the missions that particualr item can be obtained from. Cost/unite and runs/unit are there among a few other sortable columns.

Also, yes, this data is user cinntributed data and not data from the game.

**Comment by IAmPicard** [comment]
I see. I'd rather not use that data. In the past, I've found that the data in the wiki is not only unstructured (not automatically query-able), but also woefully out of date / incorrect.

That said, the wiki is publicly editable, so if someone wants to put in the effort to standardize the data in there (by assigning unique identifiers for the items, such as the symbol / id that the game API uses), we can revisit this in the future.
