### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AceMcFly** [IAmPicard/StarTrekTimelinesSpreadsheet#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (6.3.9600)**

Error details: SyntaxError: Unexpected token � in JSON at position 0

**Comment by IAmPicard** [comment]
That's very weird; was the server down perhaps? Or are you experiencing other network problems?

**Comment by AceMcFly** [comment]
installed v0.7.6 and got error message "SyntaxError: Unexpected token in json at position 0"

**Comment by AceMcFly** [comment]
network is ok

**Comment by IAmPicard** [comment]
Try deleting the entire "%APPDATA%\Star Trek Timelines Crew Management" folder on your PC and reinstalling the application.

But based on the error this looks like some sort of network or communication issue. Do you have a weird config like proxies?

**Comment by AceMcFly** [comment]
it worked! nice job... thanks...!!!!
