### ISSUE TITLE
Voyage all messed up

### ISSUE THREAD

**Issue by funkula** [IAmPicard/StarTrekTimelinesSpreadsheet#99]
**Describe the bug**
Voyage is doing this
https://imgur.com/a/SamIopP

Just keeps rotating "Hailing Starfleet" and never progresses.  When I use your app, it doesnt pull up the status of the voyage.

**To Reproduce**
Steps to reproduce the behavior:  I'll admit. I was being a little impatient.  I first had it on "thorough search" at 8, i thought it had finished, but it still said "calculating".  I then decided "UGGGH i dont have time for this" closed the app and opened it again.  It seemed normal, but then switched the setting to "quick and dirty" it pulled up some crew and i clicked forward, but it seemed to hang and didnt start the voyage.  Thats when I closed it and decided to load it on my phone to see what was going on.

**Expected behavior**
This may be totally a one off problem, but thought I'd send it in all the same.  Pretty sure this was because I used the tool haphazardly and not a STT issue.

**Screenshots**
posted earlier, but here it is again
https://imgur.com/a/SamIopP

**Additional context**
Tool version: **0.7.6**
Operating system: **win32 x64 (10.0.17134)**

**Comment by IAmPicard** [comment]
I recommend contacting DB support; I've seen other folks complain about weird voyage states, and most did not originate from the tool.

Not saying it's impossible for this to be caused by the tool, just that it happens with the regular game as well.
